import Toybox.Graphics;
import Toybox.Lang;

// port of Logic/Apps/Games/Maze.cs
//
// A 15 x 12 maze generated by depth-first backtracking, forty-five seconds to
// cross it. A and B move up and down, left and right move sideways, and the
// four Down events start an auto-repeat in that direction.
//
// The original's note, which the port inherits: "Texture2D's origin (0, 0) is
// in the lower left corner, but RectTransform's position origin is in the
// upper left corner. Maze cells call 'up' the cell with a lower Y coordinate
// than them, but the Maze is rendered using the same origin as Texture2D.
// This means that moving 'up' in the maze is seen as moving 'down' in the
// screen, and vice-versa." Everything below keeps the original's coordinates
// and flips only where it writes pixels.
class Maze extends DigiviceApp {
    const MAZE_WIDTH = 15;
    const MAZE_HEIGHT = 12;
    const PATH_WIDTH = 1;

    const CELL_PATH_UP = 0x01;
    const CELL_PATH_LEFT = 0x02;
    const CELL_PATH_DOWN = 0x04;
    const CELL_PATH_RIGHT = 0x08;
    const CELL_VISITED = 0x10;

    var currentScreen as Number = 0;    // 0 menu, 1 maze, 2 defeat, 3 victory
    var tbOptions as Array<TextBoxBuilder> = [];
    var currentOption as Number = 0;

    var cellPaths as Array<Number> = [];
    var visitedCells as Number = 0;
    var stackX as Array<Number> = [];   // the (x, y) stack, one array per axis
    var stackY as Array<Number> = [];

    var playerX as Number = -1;
    var playerY as Number = 0;
    var playerMarker as RectangleBuilder?;
    var maxTime as Number = 45;
    var timeRemaining as Number = 45;   // after defeat it runs to -1
    var tbTime as TextBoxBuilder?;
    var mazeScreen as SpriteBuilder?;

    var navigation as Fiber?;
    var countdown as Fiber?;

    function initialize(gmIn as GameManager, controllerIn, parent as ScreenElement) {
        DigiviceApp.initialize(gmIn, controllerIn, parent);
    }

    // --- Input ---

    function inputA() as Void {
        if (currentScreen == 0) {
            if (currentOption == 0) {
                startGame();
            } else if (currentOption == 1) {
                gm.audioMgr.playButtonA();
                closeApp(Kaisa.SCREEN_GAMES_TRAVEL_MENU);
            }
        } else if (currentScreen == 2 && timeRemaining == -1) {
            gm.audioMgr.playButtonA();
            closeApp(Kaisa.SCREEN_GAMES_TRAVEL_MENU);
        } else if (currentScreen == 3) {
            gm.audioMgr.playButtonA();
            gm.submitGameScore(calculateScore());
            closeApp(Kaisa.SCREEN_GAMES_TRAVEL_MENU);
        }
    }

    function inputB() as Void {
        if (currentScreen == 0) {
            gm.audioMgr.playButtonB();
            closeApp(Kaisa.SCREEN_GAMES_TRAVEL_MENU);
        } else if (currentScreen == 2 && timeRemaining == -1) {
            gm.audioMgr.playButtonA();
            closeApp(Kaisa.SCREEN_GAMES_TRAVEL_MENU);
        } else if (currentScreen == 3) {
            gm.audioMgr.playButtonA();
            gm.submitGameScore(calculateScore());
            closeApp(Kaisa.SCREEN_GAMES_TRAVEL_MENU);
        }
    }

    function inputLeft() as Void { toggleOption(); }
    function inputRight() as Void { toggleOption(); }

    function toggleOption() as Void {
        if (currentScreen == 0) {
            gm.audioMgr.playButtonA();
            currentOption = (currentOption == 0) ? 1 : 0;
            highlightSelection();
        }
    }

    // In the maze, all four buttons steer: A is up, B is down.
    function inputADown() as Void { startNavigation(Kaisa.DIR_UP); }
    function inputBDown() as Void { startNavigation(Kaisa.DIR_DOWN); }
    function inputLeftDown() as Void { startNavigation(Kaisa.DIR_LEFT); }
    function inputRightDown() as Void { startNavigation(Kaisa.DIR_RIGHT); }
    function inputAUp() as Void { stopNavigation(); }
    function inputBUp() as Void { stopNavigation(); }
    function inputLeftUp() as Void { stopNavigation(); }
    function inputRightUp() as Void { stopNavigation(); }

    function startNavigation(dir as Number) as Void {
        if (currentScreen != 1) { return; }
        stopNavigation();
        navigation = gm.runner.start(new MazeAutoNavigateDir(self, dir));
    }

    function stopNavigation() as Void {
        if (navigation != null) {
            gm.runner.stop(navigation);
            navigation = null;
        }
    }

    function dispose() as Void {
        stopNavigation();
        if (countdown != null) {
            gm.runner.stop(countdown);
            countdown = null;
        }
        DigiviceApp.dispose();
    }

    function startApp() as Void {
        drawStartMenu();
        timeRemaining = maxTime;
    }

    function calculateScore() as Number {
        return Kaisa.MathExt.roundToInt((420.0 / maxTime) * timeRemaining);
    }

    function drawStartMenu() as Void {
        tbOptions = [
            Kaisa.ScreenBuilder.buildTextBox("Start", screen, Kaisa.Font.SMALL)
                .setText("start").setSize(28, 8).setPosition(2, 8)
                .setAlignment(Kaisa.Text.ANCHOR_UPPER_CENTER)
                .setComponentSize(28, 7).setComponentPosition(0, 1),
            Kaisa.ScreenBuilder.buildTextBox("Cancel", screen, Kaisa.Font.SMALL)
                .setText("cancel").setSize(28, 8).setPosition(2, 16)
                .setAlignment(Kaisa.Text.ANCHOR_UPPER_CENTER)
                .setComponentSize(28, 7).setComponentPosition(0, 1)
        ];
        highlightSelection();
    }

    function highlightSelection() as Void {
        tbOptions[0].invertColors(currentOption == 0);
        tbOptions[1].invertColors(currentOption == 1);
    }

    function startGame() as Void {
        currentScreen = 1;
        tbOptions[0].dispose();
        tbOptions[1].dispose();
        generateMaze();
        drawMaze();

        Kaisa.ScreenBuilder.buildTextBox("Time", screen, Kaisa.Font.SMALL)
            .setText("TIME").setSize(18, 5).setPosition(1, 1);
        tbTime = Kaisa.ScreenBuilder.buildTextBox("TimeCount", screen, Kaisa.Font.SMALL)
            .setText(timeRemaining.toString()).setSize(10, 5).setPosition(22, 1);
        countdown = gm.runner.start(new MazeCountDown(self));

        playerMarker = Kaisa.ScreenBuilder.buildRectangle("Player", screen)
            .setSize(PATH_WIDTH, PATH_WIDTH).setPosition(1, 29).setFlickPeriodMs(200, true);
        updateMarkerPos();
    }

    // Returns true if a movement is made.
    function movePlayer(dir as Number) as Boolean {
        // If player enters the winning cell.
        if (playerX == MAZE_WIDTH - 1 && playerY == MAZE_HEIGHT - 1 && dir == Kaisa.DIR_RIGHT) {
            playerX += 1;
            updateMarkerPos();
            triggerWin();
            return true;
        }
        // If the player is in the starting cell.
        if (playerX == -1 && playerY == 0) {
            if (dir == Kaisa.DIR_RIGHT) {
                playerX += 1;
                updateMarkerPos();
                return true;
            }
            return false;
        } else if (playerX == MAZE_WIDTH && playerY == MAZE_HEIGHT - 1) {
            // If the player is in the end cell.
            if (dir == Kaisa.DIR_LEFT) {
                playerX -= 1;
                updateMarkerPos();
                return true;
            }
            return false;
        }

        // A regular cell.
        if (dir == Kaisa.DIR_LEFT) {
            if ((playerX == 0 && playerY == 0) || isCellConnected(playerX, playerY, dir)) {
                playerX -= 1;
                updateMarkerPos();
                return true;
            }
            return false;
        }
        if (dir == Kaisa.DIR_RIGHT) {
            // SOURCE ODDITY, reproduced: this special case tests (9, 7), the
            // exit cell of the SMALLER maze the constants used to describe
            // (the source's own comment: "1: 15, 12 / 2: 10, 8"). With the
            // 15 x 12 maze it never fires, and the exit is handled above.
            if ((playerX == 9 && playerY == 7) || isCellConnected(playerX, playerY, dir)) {
                playerX += 1;
                updateMarkerPos();
                return true;
            }
            return false;
        }
        if (dir == Kaisa.DIR_UP) {
            if (isCellConnected(playerX, playerY, dir)) {
                playerY -= 1;
                updateMarkerPos();
                return true;
            }
            return false;
        }
        if (dir == Kaisa.DIR_DOWN) {
            if (isCellConnected(playerX, playerY, dir)) {
                playerY += 1;
                updateMarkerPos();
                return true;
            }
            return false;
        }
        return false;
    }

    function updateMarkerPos() as Void {
        var posX = PATH_WIDTH + ((PATH_WIDTH + 1) * playerX);
        var posY = 7 + ((PATH_WIDTH + 1) * MAZE_HEIGHT) - 1 - ((PATH_WIDTH + 1) * playerY);
        // Place the marker correctly for the start and finish cells.
        if (posX < 0) { posX = 0; }
        if (posX > Kaisa.Constants.SCREEN_WIDTH - PATH_WIDTH) {
            posX = Kaisa.Constants.SCREEN_WIDTH - PATH_WIDTH;
        }
        if (playerMarker != null) { playerMarker.setPosition(posX, posY); }
    }

    // Depth-first backtracking, cell by cell, exactly as the original.
    function generateMaze() as Void {
        cellPaths = [];
        for (var i = 0; i < MAZE_WIDTH * MAZE_HEIGHT; i += 1) { cellPaths.add(0); }
        visitedCells = 0;
        stackX = [0];
        stackY = [0];
        cellPaths[0] = CELL_VISITED;
        visitedCells += 1;

        while (visitedCells < cellPaths.size()) {
            var top = stackX.size() - 1;
            var cx = stackX[top];
            var cy = stackY[top];

            var neighbors = [] as Array<Number>;
            if (cx > 0 && (cellPaths[neighborIndex(cx, cy, Kaisa.DIR_LEFT)] & CELL_VISITED) == 0) {
                neighbors.add(Kaisa.DIR_LEFT);
            }
            if (cx < MAZE_WIDTH - 1
                    && (cellPaths[neighborIndex(cx, cy, Kaisa.DIR_RIGHT)] & CELL_VISITED) == 0) {
                neighbors.add(Kaisa.DIR_RIGHT);
            }
            if (cy > 0 && (cellPaths[neighborIndex(cx, cy, Kaisa.DIR_UP)] & CELL_VISITED) == 0) {
                neighbors.add(Kaisa.DIR_UP);
            }
            if (cy < MAZE_HEIGHT - 1
                    && (cellPaths[neighborIndex(cx, cy, Kaisa.DIR_DOWN)] & CELL_VISITED) == 0) {
                neighbors.add(Kaisa.DIR_DOWN);
            }

            if (neighbors.size() != 0) {
                var chosen = neighbors[Kaisa.Rand.rangeInt(0, neighbors.size())];
                // "Using | instead of + makes it so adding a path that was
                // already added does not change anything."
                if (chosen == Kaisa.DIR_LEFT) {
                    cellPaths[cellIndex(cx, cy)] |= CELL_PATH_LEFT;
                    cellPaths[neighborIndex(cx, cy, Kaisa.DIR_LEFT)] |= CELL_PATH_RIGHT;
                    stackX.add(cx - 1);
                    stackY.add(cy);
                } else if (chosen == Kaisa.DIR_RIGHT) {
                    cellPaths[cellIndex(cx, cy)] |= CELL_PATH_RIGHT;
                    cellPaths[neighborIndex(cx, cy, Kaisa.DIR_RIGHT)] |= CELL_PATH_LEFT;
                    stackX.add(cx + 1);
                    stackY.add(cy);
                } else if (chosen == Kaisa.DIR_UP) {
                    cellPaths[cellIndex(cx, cy)] |= CELL_PATH_UP;
                    cellPaths[neighborIndex(cx, cy, Kaisa.DIR_UP)] |= CELL_PATH_DOWN;
                    stackX.add(cx);
                    stackY.add(cy - 1);
                } else {
                    cellPaths[cellIndex(cx, cy)] |= CELL_PATH_DOWN;
                    cellPaths[neighborIndex(cx, cy, Kaisa.DIR_DOWN)] |= CELL_PATH_UP;
                    stackX.add(cx);
                    stackY.add(cy + 1);
                }
                var nt = stackX.size() - 1;
                cellPaths[cellIndex(stackX[nt], stackY[nt])] |= CELL_VISITED;
                visitedCells += 1;
            } else {
                stackX = stackX.slice(0, stackX.size() - 1);
                stackY = stackY.slice(0, stackY.size() - 1);
            }
        }
    }

    function cellIndex(x as Number, y as Number) as Number {
        return x + (y * MAZE_WIDTH);
    }

    function neighborIndex(x as Number, y as Number, dir as Number) as Number {
        if (dir == Kaisa.DIR_LEFT) { return x - 1 + (y * MAZE_WIDTH); }
        if (dir == Kaisa.DIR_RIGHT) { return x + 1 + (y * MAZE_WIDTH); }
        if (dir == Kaisa.DIR_UP) { return x + ((y - 1) * MAZE_WIDTH); }
        if (dir == Kaisa.DIR_DOWN) { return x + ((y + 1) * MAZE_WIDTH); }
        return -1;
    }

    function isCellConnected(x as Number, y as Number, dir as Number) as Boolean {
        var cell = cellPaths[cellIndex(x, y)];
        if (dir == Kaisa.DIR_LEFT) { return (cell & CELL_PATH_LEFT) == CELL_PATH_LEFT; }
        if (dir == Kaisa.DIR_RIGHT) { return (cell & CELL_PATH_RIGHT) == CELL_PATH_RIGHT; }
        if (dir == Kaisa.DIR_UP) { return (cell & CELL_PATH_UP) == CELL_PATH_UP; }
        if (dir == Kaisa.DIR_DOWN) { return (cell & CELL_PATH_DOWN) == CELL_PATH_DOWN; }
        return false;
    }

    // BuildSpriteFromMaze: the original writes pixels into a Texture2D. Here
    // the walls are drawn into a BufferedBitmap the display list carries
    // (SpriteBuilder.runtimeBitmap), which the renderer tints and scales like
    // any other sprite.
    //
    // Two differences of expression, neither of behaviour: the original fills
    // the block white and punches paths CLEAR, which a BufferedBitmap cannot
    // do per pixel, so this draws only the wall pixels onto a transparent
    // buffer; and it fills them as horizontal runs rather than one rectangle
    // per pixel, which turns ~800 draw calls into a few dozen.
    function drawMaze() as Void {
        var bmp = null;
        try {
            bmp = Graphics.createBufferedBitmap({ :width => 32, :height => 32 }).get();
        } catch (e) {
            return;         // the pool refused; the maze draws empty
        }
        var bdc = bmp.getDc();
        bdc.setColor(0xFFFFFF, Graphics.COLOR_TRANSPARENT);

        for (var by = 7; by < 32; by += 1) {
            var runStart = -1;
            for (var bx = 0; bx <= 32; bx += 1) {
                var wall = (bx < 32) && isWallPixel(bx, by);
                if (wall && runStart < 0) {
                    runStart = bx;
                } else if (!wall && runStart >= 0) {
                    bdc.fillRectangle(runStart, by, bx - runStart, 1);
                    runStart = -1;
                }
            }
        }

        mazeScreen = Kaisa.ScreenBuilder.buildSprite("Maze", screen)
            .setSize(32, 32).setTransparent(true).setRuntimeBitmap(bmp, 32, 32);
    }

    // True where the maze block is wall. Buffer coordinates are screen
    // coordinates (y down); the original's texture coordinates run y up, so
    // texY = 31 - by.
    function isWallPixel(bx as Number, by as Number) as Boolean {
        var texY = 31 - by;
        if (texY > 24) { return false; }        // the strip the time text sits in

        // The start and the exit are punched through the border.
        if (bx == 0 && texY == 1) { return false; }
        if ((bx == 30 || bx == 31) && texY == 23) { return false; }

        var oddX = (bx % 2) == 1;
        var oddY = (texY % 2) == 1;

        if (oddX && oddY) {                     // a cell's own pixel
            var cx = (bx - 1) / 2;
            var cy = (texY - 1) / 2;
            return !(cx < MAZE_WIDTH && cy < MAZE_HEIGHT);
        }
        if (oddX && !oddY) {                    // the gap below a cell
            var cx = (bx - 1) / 2;
            var cy = (texY - 2) / 2;
            if (cx < MAZE_WIDTH && cy >= 0 && cy < MAZE_HEIGHT
                    && isCellConnected(cx, cy, Kaisa.DIR_DOWN)) {
                return false;
            }
            return true;
        }
        if (!oddX && oddY) {                    // the gap right of a cell
            var cx = (bx - 2) / 2;
            var cy = (texY - 1) / 2;
            if (cx >= 0 && cx < MAZE_WIDTH && cy < MAZE_HEIGHT
                    && isCellConnected(cx, cy, Kaisa.DIR_RIGHT)) {
                return false;
            }
            return true;
        }
        return true;                            // a corner post
    }

    function countDownTick() as Void {
        if (currentScreen == 1 || currentScreen == 2) {
            if (timeRemaining > 1) {
                timeRemaining -= 1;
                tbTime.setText(timeRemaining.toString());
            } else if (timeRemaining == 1) {
                timeRemaining -= 1;
                gm.audioMgr.playButtonB();
                currentScreen = 2;
                Kaisa.ScreenBuilder.buildTextBox("Defeat", screen, Kaisa.Font.SMALL)
                    .setText("DEFEAT").setSize(32, 11).setPosition(0, 14)
                    .setComponentSize(29, 8).setComponentPosition(3, 1);
                playerMarker.setFlickPeriodMs(0, true);
            } else if (timeRemaining == 0) {
                timeRemaining -= 1;
            }
        }
    }

    function triggerWin() as Void {
        gm.audioMgr.playButtonB();
        currentScreen = 3;
        Kaisa.ScreenBuilder.buildTextBox("Victory", screen, Kaisa.Font.SMALL)
            .setText("VICTORY").setSize(32, 7).setPosition(0, 14)
            .setComponentSize(29, 5).setComponentPosition(3, 1);
        playerMarker.setFlickPeriodMs(0, true);
    }
}

// Maze.CountDown, which the original runs on InvokeRepeating(1f, 1f).
class MazeCountDown extends Routine {
    var app as Maze;

    function initialize(appIn as Maze) {
        Routine.initialize();
        app = appIn;
    }

    function step(rt as Fiber) as Float {
        if (pc == 0) {
            pc = 1;
            return 1.0;
        }
        app.countDownTick();
        return 1.0;
    }
}

// port of Maze.AutoNavigateDir -- one move immediately, then every 0.15 s,
// with the failure beep on a wall.
class MazeAutoNavigateDir extends Routine {
    var app as Maze;
    var dir as Number;

    function initialize(appIn as Maze, dirIn as Number) {
        Routine.initialize();
        app = appIn;
        dir = dirIn;
    }

    function step(rt as Fiber) as Float {
        if (pc == 0) {
            if (!app.movePlayer(dir)) { app.gm.audioMgr.playButtonB(); }
            pc = 1;
            return 0.15;
        }
        if (!app.movePlayer(dir)) { app.gm.audioMgr.playButtonB(); }
        return 0.15;
    }
}
