import Toybox.Application;
import Toybox.Lang;
import Toybox.StringUtil;
import Toybox.System;
import Toybox.WatchUi;

// Reads the packed data blob written by tools/pack_data.py (ADR 6/7,
// ticket 12). The blob is self-describing: a small section table up
// front gives every section's byte offset and length, so nothing about
// its internal layout needs to be duplicated here except the fixed
// per-Digimon record layout, which mirrors tools/pack_data.py's ENTRY
// struct exactly:
//
//   offset  size  field
//        0  u16   number
//        2  u16   order
//        4  u8    stage
//        5  u8    spiritType
//        6  u8    element
//        7  u8    baseLevel
//        8  u8    flags (bit0 disabled, bit1 isPseudo, bit2 hasBossStats)
//        9  u8    abilityIndex (0xFF = none)
//       10  s16   evolutionIndex (-1 = none)
//       12  u16   HP
//       14  u16   EN
//       16  u16   CR
//       18  u16   AB
//       20  u8    rarity
//       21  u8    exclusive
//       22  ...   6 x 7-byte sprite refs (base, at, cr, sp, sm, bl):
//                   u8 atlasClass (0xFF = no sprite for this action)
//                   u16 x, u16 y, u8 w, u8 h
//
// Two device gotchas found while proving this format (ticket 12), kept
// here as comments because they are easy to reintroduce by accident:
//   - ByteArray.decodeNumber(UINT32, ...) returns a Long, not a Number;
//     using one as an array index throws UnexpectedTypeException.
//   - StringUtil.utf8ArrayToString rejects a ByteArray at runtime even
//     though the type annotation compiles; convertEncodedString is the
//     one that actually works.
class GameData {
    const ENTRY_SIZE = 64;      // 22-byte core + 6 x 7-byte sprite refs
    const ACTION_BASE = 0;
    const ACTION_AT = 1;
    const ACTION_CR = 2;
    const ACTION_SP = 3;
    const ACTION_SM = 4;
    const ACTION_BL = 5;

    var _bytes as ByteArray?;
    var _secOff as Array<Number> = [];
    var _secLen as Array<Number> = [];
    var _digimonCount as Number = 0;
    var _abilityCount as Number = 0;
    var _worldOff as Array<Number> = [];

    // section indices, matching tools/pack_data.py's `sections` list order
    const SEC_ENTRIES = 0;
    const SEC_NAMES = 1;
    const SEC_CODES = 2;
    const SEC_ABILITIES = 3;
    const SEC_ABILITY_SPRITES = 4;
    const SEC_ENERGY_SPRITES = 5;
    const SEC_EXTRA_EVO = 6;
    const SEC_BOSS_STATS = 7;
    const SEC_WORLDS = 8;
    const SEC_INITIALS = 9;
    const SEC_ORDER_INDEX = 10;

    function initialize() {
    }

    function load() as Void {
        // DEVICE QUIRK, found while building this (not in any wayfinder
        // ticket): concatenating Monkey C strings past a combined 65,536
        // characters silently WRAPS the result length modulo 65536 rather
        // than throwing -- confirmed empirically (70,876 chars concatenated
        // came back as 5,340 = 70,876 - 65,536, exactly). The base64 form of
        // the packed data blob is already past that boundary, so each
        // resource chunk is decoded to a ByteArray INDIVIDUALLY and the
        // (much smaller) decoded bytes are joined with ByteArray.addAll --
        // string concatenation is never used on the combined blob.
        _bytes = []b;
        var i = 0;
        while (true) {
            var sym = loadDataChunk(i);
            if (sym == null) { break; }
            var s = sym as String;
            if (s.length() > 0) {
                var chunkBytes = StringUtil.convertEncodedString(s, {
                    :fromRepresentation => StringUtil.REPRESENTATION_STRING_BASE64,
                    :toRepresentation => StringUtil.REPRESENTATION_BYTE_ARRAY
                }) as ByteArray;
                _bytes.addAll(chunkBytes);
            }
            i += 1;
        }

        var n = u16(0);
        for (var s = 0; s < n; s += 1) {
            _secOff.add(u32(2 + s * 8));
            _secLen.add(u32(6 + s * 8));
        }
        _digimonCount = _secLen[SEC_ENTRIES] / ENTRY_SIZE;
        // ability count comes from the strtable header at the start of the
        // abilities section
        _abilityCount = u16(_secOff[SEC_ABILITIES]);
        buildWorldOffsets();
    }

    // Rez.Strings.Data0, Data1, ... are generated by pack_data.py; there is
    // no dynamic string-symbol lookup in Monkey C (by design), so the
    // chunk count actually present is discovered by trying each in turn.
    function loadDataChunk(i as Number) as String? {
        if (i == 0) { return WatchUi.loadResource(Rez.Strings.Data0) as String; }
        if (i == 1) { return WatchUi.loadResource(Rez.Strings.Data1) as String; }
        if (i == 2) { return WatchUi.loadResource(Rez.Strings.Data2) as String; }
        if (i == 3) { return WatchUi.loadResource(Rez.Strings.Data3) as String; }
        if (i == 4) { return WatchUi.loadResource(Rez.Strings.Data4) as String; }
        return null;
    }

    function u8(off as Number) as Number {
        return _bytes[off];
    }
    function u16(off as Number) as Number {
        return _bytes.decodeNumber(Lang.NUMBER_FORMAT_UINT16,
            { :offset => off, :endianness => Lang.ENDIAN_LITTLE });
    }
    function s16(off as Number) as Number {
        return _bytes.decodeNumber(Lang.NUMBER_FORMAT_SINT16,
            { :offset => off, :endianness => Lang.ENDIAN_LITTLE });
    }
    function u32(off as Number) as Number {
        return _bytes.decodeNumber(Lang.NUMBER_FORMAT_UINT32,
            { :offset => off, :endianness => Lang.ENDIAN_LITTLE }).toNumber();
    }

    function digimonCount() as Number { return _digimonCount; }

    function entryOffset(idx as Number) as Number {
        return _secOff[SEC_ENTRIES] + idx * ENTRY_SIZE;
    }

    function number(idx as Number) as Number { return u16(entryOffset(idx)); }
    function order(idx as Number) as Number { return u16(entryOffset(idx) + 2); }
    function stage(idx as Number) as Number { return u8(entryOffset(idx) + 4); }
    function spiritType(idx as Number) as Number { return u8(entryOffset(idx) + 5); }
    function element(idx as Number) as Number { return u8(entryOffset(idx) + 6); }
    function baseLevel(idx as Number) as Number { return u8(entryOffset(idx) + 7); }
    function flags(idx as Number) as Number { return u8(entryOffset(idx) + 8); }
    function isDisabled(idx as Number) as Boolean { return (flags(idx) & 0x01) != 0; }
    function isPseudo(idx as Number) as Boolean { return (flags(idx) & 0x02) != 0; }
    function hasBossStats(idx as Number) as Boolean { return (flags(idx) & 0x04) != 0; }
    function abilityIndex(idx as Number) as Number { return u8(entryOffset(idx) + 9); }
    function evolutionIndex(idx as Number) as Number { return s16(entryOffset(idx) + 10); }
    function hp(idx as Number) as Number { return u16(entryOffset(idx) + 12); }
    function en(idx as Number) as Number { return u16(entryOffset(idx) + 14); }
    function cr(idx as Number) as Number { return u16(entryOffset(idx) + 16); }
    function ab(idx as Number) as Number { return u16(entryOffset(idx) + 18); }
    function rarity(idx as Number) as Number { return u8(entryOffset(idx) + 20); }
    function exclusive(idx as Number) as Boolean { return u8(entryOffset(idx) + 21) != 0; }

    // returns [atlasClass, x, y, w, h] or null if this Digimon has no
    // sprite for the given action
    function spriteRef(idx as Number, action as Number) as Array<Number>? {
        var o = entryOffset(idx) + 22 + action * 7;
        var cls = u8(o);
        if (cls == 0xFF) { return null; }
        return [cls, u16(o + 1), u16(o + 3), u8(o + 5), u8(o + 6)];
    }

    // The gallery order: row indices sorted by the editorial `order` field,
    // packed because that field does NOT follow row order (all eight stages
    // disagree; see tools/verify_gallery.py) and the alternative is sorting up
    // to 136 rows on a menu press.
    function orderCount() as Number {
        return u16(_secOff[SEC_ORDER_INDEX]);
    }

    function orderIndex(position as Number) as Number {
        return u16(_secOff[SEC_ORDER_INDEX] + 2 + position * 2);
    }

    // Boss stats are packed as a SPARSE table -- u16 count, then one
    // (index, HP, EN, CR, AB) row of u16s per Digimon that has them -- because
    // only a handful of the 593 do. Returns [HP, EN, CR, AB], or null when the
    // row has none, which is the case the model's constructor falls back on.
    function bossStats(idx as Number) as Array<Number>? {
        var base = _secOff[SEC_BOSS_STATS];
        var n = u16(base);
        for (var i = 0; i < n; i += 1) {
            var o = base + 2 + i * 10;
            if (u16(o) == idx) {
                return [u16(o + 2), u16(o + 4), u16(o + 6), u16(o + 8)];
            }
        }
        return null;
    }

    function abilitySpriteRef(abilityIdx as Number) as Array<Number>? {
        var o = _secOff[SEC_ABILITY_SPRITES] + abilityIdx * 7;
        var cls = u8(o);
        if (cls == 0xFF) { return null; }
        return [cls, u16(o + 1), u16(o + 3), u8(o + 5), u8(o + 6)];
    }

    function energySpriteRef(rank as Number) as Array<Number>? {
        var o = _secOff[SEC_ENERGY_SPRITES] + rank * 7;
        var cls = u8(o);
        if (cls == 0xFF) { return null; }
        return [cls, u16(o + 1), u16(o + 3), u8(o + 5), u8(o + 6)];
    }

    // strtable reader: u16 count, (count+1) x u16 offsets, then bytes
    function readString(sectionBase as Number, index as Number) as String {
        var count = u16(sectionBase);
        var offsTable = sectionBase + 2;
        var blobStart = offsTable + (count + 1) * 2;
        var a = u16(offsTable + index * 2);
        var b = u16(offsTable + (index + 1) * 2);
        var chars = _bytes.slice(blobStart + a, blobStart + b);
        return StringUtil.convertEncodedString(chars, {
            :fromRepresentation => StringUtil.REPRESENTATION_BYTE_ARRAY,
            :toRepresentation => StringUtil.REPRESENTATION_STRING_PLAIN_TEXT
        }) as String;
    }


    // --- worlds/areas/bosses: layout mirrors tools/pack_data.py's `wblob` ---
    //   u16 worldCount, then per world:
    //     u8 number, u8 multiMap, u8 shuffle, u8 removePlayer, u8 semibossMode,
    //     u8 showEyes, u8 lockTravel, u8 bossMode
    //     4 x 7-byte map sprite refs (Maps/<worldSprite>_0..3; class 0xFF
    //       where that map does not exist)
    //     u8 areaCount, then areaCount x (u8 number, u8 map, u32 distance,
    //                                     u8 x, u8 y)                = 8 bytes
    //     u8 bossSlotCount, then per slot: u8 nameCount, nameCount x s16
    //     u8 semibossGroupCount, then per group: u8 nameCount, nameCount x s16
    // number, multiMap, shuffle, removePlayer, semibossMode, showEyes,
    // lockTravel, bossMode, then four 7-byte map sprite refs.
    const WORLD_HEADER = 8 + 4 * 7;

    function worldCount() as Number {
        return u16(_secOff[SEC_WORLDS]);
    }

    // Where each world's header starts, computed once at load.
    //
    // The section is variable-length -- reaching world n means stepping over
    // the areas and boss lists of the n before it -- so walking it per lookup
    // is quadratic, and WorldManager.setupWorlds asks for every boss slot of
    // every world in one go. Doing that from a cold walk tripped the watchdog;
    // nine cached offsets make each lookup a table read.
    function buildWorldOffsets() as Void {
        _worldOff = [];
        var o = _secOff[SEC_WORLDS] + 2;
        var wc = worldCount();
        for (var w = 0; w < wc; w += 1) {
            _worldOff.add(o);
            o += WORLD_HEADER;
            var areaCount = u8(o); o += 1;
            o += areaCount * 8;
            var bossCount = u8(o); o += 1;
            for (var b = 0; b < bossCount; b += 1) {
                var nc = u8(o); o += 1;
                o += nc * 2;
            }
            var semiCount = u8(o); o += 1;
            for (var g = 0; g < semiCount; g += 1) {
                var nc = u8(o); o += 1;
                o += nc * 2;
            }
        }
    }

    function worldOffset(world as Number) as Number {
        return _worldOff[world];
    }

    function worldMultiMap(world as Number) as Boolean {
        return u8(worldOffset(world) + 1) != 0;
    }

    function worldShuffle(world as Number) as Boolean {
        return u8(worldOffset(world) + 2) != 0;
    }

    function worldRemovePlayer(world as Number) as Boolean {
        return u8(worldOffset(world) + 3) != 0;
    }

    // 0 none, 1 Fill, 2 Gank, 3 Pseudo
    function worldSemibossMode(world as Number) as Number {
        return u8(worldOffset(world) + 4);
    }

    function worldShowEyes(world as Number) as Boolean {
        return u8(worldOffset(world) + 5) != 0;
    }

    // "If true, the player can't travel between areas, areas will be traveled
    // in order, and datastorms can't happen."
    function worldLockTravel(world as Number) as Boolean {
        return u8(worldOffset(world) + 6) != 0;
    }

    // 0 Evolve, 1 UseBurst
    function worldBossMode(world as Number) as Number {
        return u8(worldOffset(world) + 7);
    }

    // The world's map art, 0..3; null where a single-map world has no such map.
    function worldMapSprite(world as Number, map as Number) as Array<Number>? {
        var o = worldOffset(world) + 8 + map * 7;
        var cls = u8(o);
        if (cls == 0xFF) { return null; }
        return [cls, u16(o + 1), u16(o + 3), u8(o + 5), u8(o + 6)];
    }

    function worldAreaCount(world as Number) as Number {
        return u8(worldOffset(world) + WORLD_HEADER);
    }

    // [number, map, distance, x, y] for one area.
    // The journey is walked with the watch's own step count, one game step per
    // real step, where the original took one step per six shakes of a phone.
    // Six real steps for one is a different kind of walk -- a shake is a flick
    // of the wrist, a step is a step -- so the distances come down by the same
    // six instead: an area 6,000 long is 1,000 to walk.
    const DISTANCE_SCALE = 6;

    function areaDistance(world as Number, area as Number) as Number {
        var distance = worldArea(world, area)[2] / DISTANCE_SCALE;
        return (distance < 1) ? 1 : distance;
    }

    function worldArea(world as Number, area as Number) as Array<Number> {
        var o = worldOffset(world) + WORLD_HEADER + 1 + area * 8;
        return [u8(o), u8(o + 1), u32(o + 2), u8(o + 6), u8(o + 7)];
    }

    // The Digimon indices in one boss slot (usually one, more where the slot
    // is a choice), and the same for a semiboss group.
    function worldBossSlotCount(world as Number) as Number {
        var o = worldOffset(world) + WORLD_HEADER;
        var areaCount = u8(o); o += 1 + areaCount * 8;
        return u8(o);
    }

    function worldBossSlot(world as Number, slot as Number) as Array<Number> {
        var o = worldOffset(world) + WORLD_HEADER;
        var areaCount = u8(o); o += 1 + areaCount * 8;
        var count = u8(o); o += 1;
        for (var b = 0; b < count; b += 1) {
            var nc = u8(o); o += 1;
            if (b == slot) {
                var out = [] as Array<Number>;
                for (var i = 0; i < nc; i += 1) { out.add(s16(o + i * 2)); }
                return out;
            }
            o += nc * 2;
        }
        return [];
    }

    function worldSemibossGroupCount(world as Number) as Number {
        var o = semibossOffset(world);
        return u8(o);
    }

    function worldSemibossGroup(world as Number, group as Number) as Array<Number> {
        var o = semibossOffset(world);
        var count = u8(o); o += 1;
        for (var g = 0; g < count; g += 1) {
            var nc = u8(o); o += 1;
            if (g == group) {
                var out = [] as Array<Number>;
                for (var i = 0; i < nc; i += 1) { out.add(s16(o + i * 2)); }
                return out;
            }
            o += nc * 2;
        }
        return [];
    }

    function semibossOffset(world as Number) as Number {
        var o = worldOffset(world) + WORLD_HEADER;
        var areaCount = u8(o); o += 1 + areaCount * 8;
        var bossCount = u8(o); o += 1;
        for (var b = 0; b < bossCount; b += 1) {
            var nc = u8(o); o += 1;
            o += nc * 2;
        }
        return o;
    }

    // Walks the variable-length worlds section once and returns the totals
    // that size the save format: [areaTotal, bossListTotal, worldCount].
    //
    // bossListTotal is NOT the number of boss slots. WorldManager.SetupWorlds
    // builds each world's boss list from its slots and then, in Fill mode,
    // APPENDS the chosen semiboss group -- so a world's list can be longer
    // than its slot count, and the save has to hold the longest it could be.
    // SPEC section 8 listed this as unchecked; it is now sized from the data.
    //
    // The third total is one entry per world: the original's
    // SemibossGroupForEachMap is indexed by world, not by group.
    function worldTotals() as Array<Number> {
        var o = _secOff[SEC_WORLDS] + 2;
        var areaTotal = 0;
        var bossTotal = 0;
        var wc = worldCount();
        for (var w = 0; w < wc; w += 1) {
            o += WORLD_HEADER;
            var areaCount = u8(o); o += 1;
            areaTotal += areaCount;
            o += areaCount * 8;              // 1+1+4+1+1
            var bossCount = u8(o); o += 1;
            var listLength = bossCount;
            for (var b = 0; b < bossCount; b += 1) {
                var nc = u8(o); o += 1;
                o += nc * 2;
            }
            var semiCount = u8(o); o += 1;
            var biggestGroup = 0;
            for (var g = 0; g < semiCount; g += 1) {
                var nc = u8(o); o += 1;
                if (nc > biggestGroup) { biggestGroup = nc; }
                o += nc * 2;
            }
            bossTotal += listLength + biggestGroup;
        }
        return [areaTotal, bossTotal, wc];
    }

    // Where a world's slice starts in the save's flat per-world arrays.
    function worldAreaOffset(world as Number) as Number {
        var total = 0;
        for (var w = 0; w < world; w += 1) { total += worldAreaCount(w); }
        return total;
    }

    // The same for the boss list, whose per-world length is its slot count
    // plus the biggest semiboss group it could be filled with.
    function worldBossListLength(world as Number) as Number {
        var count = worldBossSlotCount(world);
        var groups = worldSemibossGroupCount(world);
        var biggest = 0;
        for (var g = 0; g < groups; g += 1) {
            var size = worldSemibossGroup(world, g).size();
            if (size > biggest) { biggest = size; }
        }
        return count + biggest;
    }

    function worldBossOffset(world as Number) as Number {
        var total = 0;
        for (var w = 0; w < world; w += 1) { total += worldBossListLength(w); }
        return total;
    }

    // The initial Digimon a new game can start the player's enemy as:
    // initials.json, packed as a u16 count and a u16 index each.
    function initialCount() as Number {
        return u16(_secOff[SEC_INITIALS]);
    }

    function initial(i as Number) as Number {
        return u16(_secOff[SEC_INITIALS] + 2 + i * 2);
    }

    function name(idx as Number) as String {
        return readString(_secOff[SEC_NAMES], idx);
    }

    function abilityName(idx as Number) as String {
        return readString(_secOff[SEC_ABILITIES], idx);
    }

    // Finds a Digimon by its five-character code WITHOUT decoding any string.
    //
    // The obvious version -- decode every row's code and compare -- is 593
    // string decodes, and a scan of that shape already tripped the watchdog
    // once (Database.indexOfName, before the well-known indices moved to build
    // time). The codes are fixed-width, NUL-padded ASCII in the blob, so the
    // comparison happens on raw bytes and the app never builds a string it
    // does not display.
    function indexOfCodeBytes(wanted as ByteArray) as Number {
        var base = _secOff[SEC_CODES];
        var n = _digimonCount;
        for (var i = 0; i < n; i += 1) {
            var o = base + i * 5;
            var match = true;
            for (var k = 0; k < 5; k += 1) {
                var want = (k < wanted.size()) ? wanted[k] : 0;
                if (_bytes[o + k] != want) { match = false; break; }
            }
            if (match) { return i; }
        }
        return -1;
    }

    function code(idx as Number) as String {
        var o = _secOff[SEC_CODES] + idx * 5;
        // ljust-padded to 5 bytes with NUL in the packer; find the real length
        // before converting (Monkey C string literals don\'t take a "\0" escape,
        // and NUL-terminated conversion behaviour isn\'t documented, so this is
        // trimmed at the byte level instead of trusting the string form).
        var len = 5;
        for (var i = 0; i < 5; i += 1) {
            if (_bytes[o + i] == 0) { len = i; break; }
        }
        var chars = _bytes.slice(o, o + len);
        return StringUtil.convertEncodedString(chars, {
            :fromRepresentation => StringUtil.REPRESENTATION_BYTE_ARRAY,
            :toRepresentation => StringUtil.REPRESENTATION_STRING_PLAIN_TEXT
        }) as String;
    }
}
