import Toybox.Lang;
import Toybox.StringUtil;
import Toybox.WatchUi;

// GENERATED by tools/pack_sounds.py from the source MP3s -- do not
// edit. Regenerate with `tools/pack_sounds.py`.
//
// Every sound is a sequence of (frequency Hz, duration ms) notes,
// extracted from the source's own square-wave audio (ticket 03 of
// .scratch/sound-and-vibration/map.md). freq 0 is a rest.
//
// Notes are packed as bytes (UINT16 freq, UINT16 dur, little-endian)
// and carried as base64 in string resources -- the same move ADR 6
// makes for the Digimon database, forced here by the same wall: a
// literal array past a few thousand elements overflows monkeyc's
// const type checker (a real StackOverflowError, not a heap limit).
// NAMES[i] -> OFFSETS[i]/COUNTS[i] index into the decoded bytes,
// 4 bytes per note.
module Kaisa {
    module Sounds {
        const NAMES = [
            "attackTravelVeryLong", "beepLow", "buttonA", "buttonB",
            "changeDock", "charHappy", "charSad", "deport",
            "deportSpirit", "destroySpirits", "digiHunter_Start", "digiPowerFailed",
            "digiPowerSucceed", "digistorm", "encounterDigimon", "encounterDigimonBoss",
            "evolutionAncient", "evolutionRegular", "evolutionSpirit", "explosion",
            "gameStart", "launchAttack", "launchAttackLong", "levelDown",
            "levelDownDigimon", "levelUp", "loseDigimon", "punishment",
            "reward", "speedRunner_Asteroid", "speedRunner_Crash", "speedRunner_Finish",
            "speedRunner_Start", "stealAllSpirits", "summonDigimon", "travelMap",
            "triggerEvent", "unlockCode", "unlockDigimon", "unpleasantBeep",
        ];
        const OFFSETS = [
            0, 158, 161, 162, 163, 213, 220, 223,
            233, 253, 264, 284, 315, 370, 1024, 1033,
            1054, 1187, 1231, 1387, 1406, 1636, 1642, 1658,
            1677, 1729, 1747, 1753, 1780, 1806, 1811, 1815,
            1825, 1840, 1916, 1954, 1994, 2004, 2032, 2052,
        ];
        const COUNTS = [
            158, 3, 1, 1, 50, 7, 3, 10,
            20, 11, 20, 31, 55, 654, 9, 21,
            133, 44, 156, 19, 230, 6, 16, 19,
            52, 18, 6, 27, 26, 5, 4, 10,
            15, 76, 38, 40, 10, 28, 20, 1,
        ];

        var _bytes as ByteArray?;
        var _byName as Dictionary? = null;

        // Decode on first note. Menu and watch builds never need this table,
        // and callers must not depend on a separate startup call.
        function load() as Void {
            _bytes = []b;
            var i = 0;
            while (true) {
                var sym = loadChunk(i);
                if (sym == null) { break; }
                var s = sym as String;
                if (s.length() > 0) {
                    var chunkBytes = StringUtil.convertEncodedString(s, {
                        :fromRepresentation => StringUtil.REPRESENTATION_STRING_BASE64,
                        :toRepresentation => StringUtil.REPRESENTATION_BYTE_ARRAY
                    }) as ByteArray;
                    (_bytes as ByteArray).addAll(chunkBytes);
                }
                i += 1;
            }
        }

        function loadChunk(i as Number) as String? {
        if (i == 0) { return WatchUi.loadResource(Rez.Strings.SoundData0) as String; }
        if (i == 1) { return WatchUi.loadResource(Rez.Strings.SoundData1) as String; }
            return null;
        }

        // Call sites resolve their string through this rather than a linear scan.
        function indexOf(name as String) as Number {
            if (_byName == null) {
                var d = {};
                for (var i = 0; i < NAMES.size(); i += 1) { d[NAMES[i]] = i; }
                _byName = d;
            }
            var idx = _byName.get(name);
            return (idx == null) ? -1 : idx;
        }

        // (frequency Hz, duration ms) for note `n` of sound `soundIndex`;
        // freq 0 is a rest.
        function noteAt(soundIndex as Number, n as Number) as Array<Number> {
            if (_bytes == null) { load(); }
            var off = (OFFSETS[soundIndex] + n) * 4;
            var bytes = _bytes as ByteArray;
            var freq = bytes.decodeNumber(Lang.NUMBER_FORMAT_UINT16,
                { :offset => off, :endianness => Lang.ENDIAN_LITTLE });
            var dur = bytes.decodeNumber(Lang.NUMBER_FORMAT_UINT16,
                { :offset => off + 2, :endianness => Lang.ENDIAN_LITTLE });
            return [freq, dur];
        }
    }
}
