import Toybox.Lang;

// GENERATED by tools/gen_wellknown.py -- do not edit.
//
// The only Digimon the source names as string literals, resolved to
// their packed-data indices at build time. Resolving them at runtime
// tripped the watchdog: each lookup is a linear scan of 593 rows and
// every row's name is a base64-backed string decode.
module Kaisa {
    module WellKnown {
        // Constants.DEFAULT_DIGIMON = "numemon"
        const DEFAULT_DIGIMON = 19;
        // Constants.DEFAULT_SPIRIT_DIGIMON = "flamemon"
        const DEFAULT_SPIRIT_DIGIMON = 462;

        // Database.SetupPlayerSpirit, in GameChar order.
        const PLAYER_SPIRIT = [
            396,   // Takuya: agunimon
            398,   // Koji: lobomon
            402,   // Zoe: kazemon
            400,   // JP: beetlemon
            404,   // Tommy: kumamon
            426,   // Koichi: loweemon
        ];
    }
}
