#!/usr/bin/env python3
"""Resolve the handful of Digimon the source names as literals, at pack time.

The original addresses Digimon by name everywhere and looks them up with a
linear string compare. The port addresses them by index (ADR 7), which leaves
exactly eight literal names to resolve: Constants.DEFAULT_DIGIMON,
Constants.DEFAULT_SPIRIT_DIGIMON, and the six Database.SetupPlayerSpirit
entries.

Doing it at runtime cost the app its startup: 593 rows x a base64-backed
string decode per lookup tripped the watchdog on the first one
("Watchdog Tripped Error - Code Executed Too Long"). Doing it here costs
nothing and removes the last name lookup from the boot path.

The names are parsed from the C# rather than typed here, so changing
DEFAULT_DIGIMON in the source changes the port (ADR 12).

Output: app/source/Data/WellKnown.mc
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import src, app as app_path

CONSTANTS_CS = "Assets/Scripts/Constants.cs"
DATABASE_CS = "Assets/Scripts/Logic/Data/Database.cs"
PLAYER_CHARACTER_CS = "Assets/Scripts/Logic/PlayerCharacter.cs"
DIGIMON_DB = "Assets/Resources/digimonDB.json"


def read(path):
    return open(src(path), encoding="utf-8-sig", errors="replace").read()


def main():
    db = json.load(open(src(DIGIMON_DB)))
    index_of = {}
    for i, row in enumerate(db):
        index_of[row["name"].lower()] = i

    consts = read(CONSTANTS_CS)
    defaults = {}
    for key in ("DEFAULT_DIGIMON", "DEFAULT_SPIRIT_DIGIMON"):
        m = re.search(rf'{key}\s*=\s*"([^"]+)"', consts)
        if not m:
            raise SystemExit(f"{key} not found in {CONSTANTS_CS}")
        defaults[key] = m.group(1).lower()

    # GameChar's declaration order is the order the port's enum uses; `none`
    # is -1 and is not a spirit slot.
    chars = re.search(r"enum GameChar \{(.*?)\}", read(PLAYER_CHARACTER_CS), re.S).group(1)
    order = [c.strip().split("=")[0].strip() for c in chars.split(",")]
    order = [c for c in order if c and c != "none"]

    spirits_src = read(DATABASE_CS)
    spirits = dict(re.findall(r'PlayerSpirit\[GameChar\.(\w+)\]\s*=\s*"([^"]+)"',
                              spirits_src))
    missing = [c for c in order if c not in spirits]
    if missing:
        raise SystemExit(f"no PlayerSpirit entry for {missing}")

    def resolve(name):
        if name not in index_of:
            raise SystemExit(f"{name!r} is not a row of digimonDB.json")
        return index_of[name]

    lines = [
        "import Toybox.Lang;",
        "",
        "// GENERATED by tools/gen_wellknown.py -- do not edit.",
        "//",
        "// The only Digimon the source names as string literals, resolved to",
        "// their packed-data indices at build time. Resolving them at runtime",
        "// tripped the watchdog: each lookup is a linear scan of 593 rows and",
        "// every row's name is a base64-backed string decode.",
        "module Kaisa {",
        "    module WellKnown {",
        f"        // Constants.DEFAULT_DIGIMON = \"{defaults['DEFAULT_DIGIMON']}\"",
        f"        const DEFAULT_DIGIMON = {resolve(defaults['DEFAULT_DIGIMON'])};",
        f"        // Constants.DEFAULT_SPIRIT_DIGIMON = \"{defaults['DEFAULT_SPIRIT_DIGIMON']}\"",
        f"        const DEFAULT_SPIRIT_DIGIMON = {resolve(defaults['DEFAULT_SPIRIT_DIGIMON'])};",
        "",
        "        // Database.SetupPlayerSpirit, in GameChar order.",
        "        const PLAYER_SPIRIT = [",
    ]
    for c in order:
        name = spirits[c].lower()
        lines.append(f"            {resolve(name)},   // {c}: {name}")
    lines += [
        "        ];",
        "    }",
        "}",
        "",
    ]
    open(app_path("source/Data/WellKnown.mc"), "w").write("\n".join(lines))
    print(f"wrote app/source/Data/WellKnown.mc "
          f"(2 defaults, {len(order)} player spirits)")


if __name__ == "__main__":
    main()
