#!/usr/bin/env python3
"""Generate the font-metrics probe scene from tools/text_probe.json.

The same JSON drives tools/verify_text.py, which computes what the scene must
look like on screen. Generating one side and computing the other from a single
spec is the point (ADR 12): a check transcribed twice checks the transcription.

Output: app/source/Render/TextProbe.mc
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import app as app_path

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FACE_CONST = {"Big": "Kaisa.Screen.FONT_BIG",
              "Regular": "Kaisa.Screen.FONT_REGULAR",
              "Small": "Kaisa.Screen.FONT_SMALL"}
ANCHOR_CONST = ["Kaisa.Text.ANCHOR_UPPER_LEFT",
                "Kaisa.Text.ANCHOR_UPPER_CENTER",
                "Kaisa.Text.ANCHOR_UPPER_RIGHT"]


def main():
    spec = json.load(open(os.path.join(ROOT, "tools", "text_probe.json")))
    lines = [
        "import Toybox.Lang;",
        "",
        "// GENERATED by tools/gen_text_probe.py from tools/text_probe.json --",
        "// do not edit. The same spec tells tools/verify_text.py what this",
        "// scene must look like once drawn, so the check cannot drift from the",
        "// thing it checks (ADR 12).",
        "//",
        "// Every box is 6 game pixels tall, which is one line of Regular or",
        "// Small and clears Big's 7 px digits without overlapping the next.",
        "module TextProbe {",
        "    const BOX_HEIGHT = 6;",
        "",
        "    function build(root as ContainerBuilder) as Void {",
    ]
    for s in spec["strings"]:
        text = s["text"].replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        lines += [
            f'        // {s["why"]}',
            f'        add(root, "{text}", {FACE_CONST[s["face"]]},',
            f'            {s["x"]}, {s["y"]}, {s["w"]}, {ANCHOR_CONST[s["anchor"]]}, '
            f'{"true" if s["inverted"] else "false"});',
        ]
    lines += [
        "    }",
        "",
        "    function add(root as ContainerBuilder, text as String, font as Number,",
        "                 x as Number, y as Number, w as Number, anchor as Number,",
        "                 inverted as Boolean) as Void {",
        "        var box = new TextBoxBuilder();",
        '        box.setName("Probe");',
        "        box.setSize(w, BOX_HEIGHT)",
        "           .setPosition(x, y)",
        "           .setFont(font)",
        "           .setAlignment(anchor)",
        "           .setTransparent(!inverted)",
        "           .invertColors(inverted)",
        "           .setText(text);",
        "        root.addChild(box);",
        "    }",
        "}",
        "",
    ]
    path = app_path("source/Render/TextProbe.mc")
    open(path, "w").write("\n".join(lines))
    print(f"wrote app/source/Render/TextProbe.mc ({len(spec['strings'])} strings)")


if __name__ == "__main__":
    main()
