#!/usr/bin/env python3
"""Resolve the handful of Digimon the source names as literals, at pack time.

The original addresses Digimon by name everywhere and looks them up with a
linear string compare. The port addresses them by index (ADR 7), which leaves
exactly eight literal names to resolve: Constants.DEFAULT_DIGIMON,
Constants.DEFAULT_SPIRIT_DIGIMON, and the six Database.SetupPlayerSpirit
entries.

Doing it at runtime cost the app its startup: 593 rows x a base64-backed
string decode per lookup tripped the watchdog on the first one
("Watchdog Tripped Error - Code Executed Too Long"). Doing it here costs
nothing and removes the last name lookup from the boot path.

The names are parsed from the C# rather than typed here, so changing
DEFAULT_DIGIMON in the source changes the port (ADR 12).

Output: app/source/Data/WellKnown.mc
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import src, app as app_path

ANIMATIONS_CS = "Assets/Scripts/Logic/Data/Animations.cs"
DIGIMON_CS = "Assets/Scripts/Logic/Models/Digimon.cs"
GAME_MANAGER_CS = "Assets/Scripts/GameManager.cs"
CONSTANTS_CS = "Assets/Scripts/Constants.cs"
DATABASE_CS = "Assets/Scripts/Logic/Data/Database.cs"
PLAYER_CHARACTER_CS = "Assets/Scripts/Logic/PlayerCharacter.cs"
DIGIMON_DB = "Assets/Resources/digimonDB.json"


def read(path):
    return open(src(path), encoding="utf-8-sig", errors="replace").read()


def main():
    db = json.load(open(src(DIGIMON_DB)))
    index_of = {}
    for i, row in enumerate(db):
        index_of[row["name"].lower()] = i

    consts = read(CONSTANTS_CS)
    defaults = {}
    for key in ("DEFAULT_DIGIMON", "DEFAULT_SPIRIT_DIGIMON"):
        m = re.search(rf'{key}\s*=\s*"([^"]+)"', consts)
        if not m:
            raise SystemExit(f"{key} not found in {CONSTANTS_CS}")
        defaults[key] = m.group(1).lower()

    # GameChar's declaration order is the order the port's enum uses; `none`
    # is -1 and is not a spirit slot.
    chars = re.search(r"enum GameChar \{(.*?)\}", read(PLAYER_CHARACTER_CS), re.S).group(1)
    order = [c.strip().split("=")[0].strip() for c in chars.split(",")]
    order = [c for c in order if c and c != "none"]

    spirits_src = read(DATABASE_CS)
    spirits = dict(re.findall(r'PlayerSpirit\[GameChar\.(\w+)\]\s*=\s*"([^"]+)"',
                              spirits_src))
    missing = [c for c in order if c not in spirits]
    if missing:
        raise SystemExit(f"no PlayerSpirit entry for {missing}")

    def resolve(name):
        if name not in index_of:
            raise SystemExit(f"{name!r} is not a row of digimonDB.json")
        return index_of[name]

    anims = read(ANIMATIONS_CS)
    ancient, fusion = ancient_pairs(anims), fusion_sets(anims)
    susanoo = susanoo_names(anims)
    elements, element_sets = element_values(read(DIGIMON_CS)), \
        fusion_elements(read(GAME_MANAGER_CS))

    lines = [
        "import Toybox.Lang;",
        "",
        "// GENERATED by tools/gen_wellknown.py -- do not edit.",
        "//",
        "// The only Digimon the source names as string literals, resolved to",
        "// their packed-data indices at build time. Resolving them at runtime",
        "// tripped the watchdog: each lookup is a linear scan of 593 rows and",
        "// every row's name is a base64-backed string decode.",
        "module Kaisa {",
        "    module WellKnown {",
        f"        // Constants.DEFAULT_DIGIMON = \"{defaults['DEFAULT_DIGIMON']}\"",
        f"        const DEFAULT_DIGIMON = {resolve(defaults['DEFAULT_DIGIMON'])};",
        f"        // Constants.DEFAULT_SPIRIT_DIGIMON = \"{defaults['DEFAULT_SPIRIT_DIGIMON']}\"",
        f"        const DEFAULT_SPIRIT_DIGIMON = {resolve(defaults['DEFAULT_SPIRIT_DIGIMON'])};",
        "",
        "        // Database.SetupPlayerSpirit, in GameChar order.",
        "        const PLAYER_SPIRIT = [",
    ]
    for c in order:
        name = spirits[c].lower()
        lines.append(f"            {resolve(name)},   // {c}: {name}")
    lines += ["        ];", ""]

    # AncientEvolution's switch: which two spirits an ancient Digimon is made
    # of. Rows are {ancient, human spirit, animal spirit}, in source order.
    lines.append("        // Animations.AncientEvolution's switch over the ancient's name.")
    lines.append("        const ANCIENT_SPIRITS = [")
    for anc, human, animal in ancient:
        lines.append(f"            [{resolve(anc)}, {resolve(human)}, {resolve(animal)}],"
                     f"   // {anc}: {human} + {animal}")
    lines += ["        ];", ""]

    # FusionSpiritEvolution's two branches: ten small spirits each, five human
    # then five animal, and the Digimon whose name picks the first branch.
    trigger, branches = fusion
    lines.append("        // Animations.FusionSpiritEvolution: the branch is chosen by")
    lines.append(f"        // `digimon == \"{trigger}\"`.")
    lines.append(f"        const FUSION_TRIGGER = {resolve(trigger)};")
    for label, key in (("HUMANS", "humans"), ("ANIMALS", "animals")):
        lines.append(f"        const FUSION_{label} = [")
        for branch in branches:
            names = branch[key]
            idx = ", ".join(str(resolve(n)) for n in names)
            lines.append(f"            [{idx}],   // {', '.join(names)}")
        lines += ["        ];"]

    # The number of rows at stage Spirit. The save's lost-spirit list is
    # capped, and this is the ceiling that cannot truncate one: a spirit is
    # locked when it is lost, so each can be in the list at most once.
    spirits = sum(1 for row in db if row.get("stage") == 6)
    lines.append(f"        // Rows at stage Spirit, which caps the saved lost-spirit list.")
    lines.append(f"        const SPIRIT_ROWS = {spirits};")
    lines += [""]

    # SusanoomonEvolution names the two fusions it shows, the Digimon it forms,
    # and all ten spirits of each kind in the order they appear.
    lines.append("        // Animations.SusanoomonEvolution's Digimon, by name.")
    lines.append(f"        const SUSANOOMON = {resolve(susanoo['susanoomon'])};"
                 f"   // {susanoo['susanoomon']}")
    for key in ("kaisergreymon", "magnagarurumon"):
        lines.append(f"        const {key.upper()} = {resolve(susanoo[key])};   // {key}")
    for label in ("humans", "animals"):
        names = susanoo[label]
        idx = ", ".join(str(resolve(n)) for n in names)
        lines.append(f"        const SUSANOO_{label.upper()} = [{idx}];")
        lines.append(f"        // {', '.join(names)}")
    lines += [""]

    # GameManager.HasAllSpiritsForFusion: each of the two named fusions counts
    # the spirits of five elements; every other fusion counts all twenty.
    lines.append("        // GameManager.HasAllSpiritsForFusion's element sets.")
    lines.append("        const FUSION_ELEMENTS = [")
    for name, els in element_sets:
        vals = ", ".join(str(elements[e]) for e in els)
        lines.append(f"            [{resolve(name)}, [{vals}]],   // {name}: "
                     f"{', '.join(els)}")
    lines += ["        ];"]

    lines += [
        "    }",
        "}",
        "",
    ]
    open(app_path("source/Data/WellKnown.mc"), "w").write("\n".join(lines))
    print(f"wrote app/source/Data/WellKnown.mc "
          f"(2 defaults, {len(order)} player spirits, {len(ancient)} ancients, "
          f"{sum(len(b['humans']) + len(b['animals']) for b in branches)} fusion spirits)")


def element_values(consts):
    """Element's declaration order, which is the value the packed data holds."""
    body = re.search(r"enum Element \{(.*?)\}", consts, re.S)
    if not body:
        raise SystemExit("enum Element not found in Digimon.cs")
    names = [e.strip().split("=")[0].strip() for e in body.group(1).split(",")]
    return {n: i for i, n in enumerate(n for n in names if n)}


def fusion_elements(gm_cs):
    """The (fusion, elements) pairs HasAllSpiritsForFusion branches on."""
    start = gm_cs.index("bool HasAllSpiritsForFusion(")
    body = gm_cs[start:gm_cs.index("public bool IsInDock", start)]
    out = []
    for name, block in re.findall(
            r'if \(fusionName == "(\w+)"\) \{(.*?)\n            \}', body, re.S):
        els = re.findall(r"d\.element == Element\.(\w+)", block)
        if len(els) != 5:
            raise SystemExit(f"{name}'s element list did not parse")
        out.append((name, els))
    if len(out) != 2:
        raise SystemExit("HasAllSpiritsForFusion should name two fusions")
    return out


def susanoo_names(anims):
    """SusanoomonEvolution's literals: the two fusions, Susanoomon, the spirits."""
    body = method_body(anims, "SusanoomonEvolution")
    out = {}
    m = re.search(r'GetAllDigimonSprites\("(\w+)"\)', body)
    if not m:
        raise SystemExit("SusanoomonEvolution's Digimon did not parse")
    out["susanoomon"] = m.group(1)
    for key in ("kaisergreymon", "magnagarurumon"):
        if f'GetDigimonSprite("{key}"' not in body:
            raise SystemExit(f"SusanoomonEvolution does not name {key}")
        out[key] = key
    for label, var in (("humans", "sHumans"), ("animals", "sAnimals")):
        pairs = re.findall(
            rf'{var}\[(\d+)\] = spriteDB\.GetDigimonSprite\("(\w+)", SpriteAction\.SpiritSmall\);',
            body)
        if len(pairs) != 10:
            raise SystemExit(f"SusanoomonEvolution's {var} did not parse")
        out[label] = [n for _, n in sorted(pairs, key=lambda p: int(p[0]))]
    return out


def method_body(text, name):
    """The source of one coroutine, from its signature to the next one."""
    start = text.index(f"IEnumerator {name}(")
    end = text.find("public static IEnumerator", start + 1)
    return text[start:end if end != -1 else len(text)]


def ancient_pairs(anims):
    """AncientEvolution's switch, as (ancient, human, animal) in source order."""
    body = method_body(anims, "AncientEvolution")
    cases = re.findall(
        r'case "(\w+)":\s*'
        r'sHumanSpirit = spriteDB\.GetDigimonSprite\("(\w+)", SpriteAction\.Spirit\);\s*'
        r'sAnimalSpirit = spriteDB\.GetDigimonSprite\("(\w+)", SpriteAction\.Spirit\);',
        body)
    if not cases:
        raise SystemExit("AncientEvolution's switch did not parse")
    return cases


def fusion_sets(anims):
    """FusionSpiritEvolution's two branches, and the name that picks the first."""
    body = method_body(anims, "FusionSpiritEvolution")
    trigger = re.search(r'if \(digimon == "(\w+)"\)', body)
    if not trigger:
        raise SystemExit("FusionSpiritEvolution's branch condition did not parse")
    branches = []
    for part in re.split(r"\belse\b", body[trigger.end():], maxsplit=1):
        humans = re.findall(
            r'sHumans\[\d\] = spriteDB\.GetDigimonSprite\("(\w+)", SpriteAction\.SpiritSmall\);',
            part)
        animals = re.findall(
            r'sAnimals\[\d\] = spriteDB\.GetDigimonSprite\("(\w+)", SpriteAction\.SpiritSmall\);',
            part)
        if len(humans) != 5 or len(animals) != 5:
            raise SystemExit("FusionSpiritEvolution's spirit lists did not parse")
        branches.append({"humans": humans, "animals": animals})
    if len(branches) != 2:
        raise SystemExit("FusionSpiritEvolution should have two branches")
    return trigger.group(1), branches


if __name__ == "__main__":
    main()
