#!/usr/bin/env python3
"""Reuse the baked menu lettering for labels added by the watch port.

Reads the packed UI references rather than assuming fixed atlas positions.
The F is the same three-pixel glyph from the existing Small face. All other
letters come directly from the original menu art; no extra bitmap is needed.
"""
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]

# character: (sprite name, local x, local y, ink width)
LETTERS = {
    "A": ("mainMenu_2", 11, 24, 4),
    "B": ("mainMenu_3", 18, 27, 3),
    "C": ("mainMenu_6", 1, 24, 3),
    "D": ("mainMenu_3", 9, 21, 4),
    "E": ("mainMenu_2", 22, 24, 3),
    "G": ("mainMenu_2", 6, 24, 4),
    "I": ("mainMenu_3", 14, 21, 1),
    "L": ("game_sections_2", 27, 24, 4),
    "M": ("mainMenu_2", 16, 24, 5),
    "N": ("mainMenu_6", 10, 24, 4),
    "O": ("mainMenu_6", 5, 24, 4),
    "P": ("mainMenu_5", 22, 24, 4),
    "R": ("game_sections_1", 2, 24, 4),
    "S": ("mainMenu_1", 4, 24, 3),
    "T": ("mainMenu_1", 8, 24, 3),
    "U": ("mainMenu_1", 20, 24, 3),
    "V": ("game_sections_2", 17, 24, 5),
}


def main():
    sprites = json.loads((ROOT / "build/ui_sprite_names.json").read_text())
    fonts = json.loads((ROOT / "build/font_index.json").read_text())
    atlas = Image.open(ROOT / "app/resources/drawables/atlas_32x32.png").convert("RGBA")
    glyphs = {}
    for char, (name, x, y, width) in LETTERS.items():
        cls, sx, sy, _, _ = sprites[name]
        assert cls == 1
        crop = atlas.crop((sx + x, sy + y, sx + x + width, sy + y + 5))
        assert crop.getbbox() == (0, 0, width, 5), (char, name)
        glyphs[ord(char)] = [sx + x, width, 5, width + 1, 0, sy + y, cls]
    f = next(g for g in fonts["Small"]["glyphs"] if g["char"] == "F")
    glyphs[ord("F")] = [f["x"], f["w"], f["h"], f["w"] + 1, 0, 0, 6]
    # One blank column plus the previous letter's gutter gives a two-pixel
    # word gap, instead of the text faces' four-pixel visible gap.
    glyphs[32] = [0, 0, 5, 1, 0, 0, 1]
    lines = [
        "import Toybox.Lang;", "",
        "// GENERATED by tools/pack_menu_font.py from the original menu art.",
        "// Run after packing UI sprites and fonts; do not edit by hand.",
        "module Kaisa {", "    module MenuFont {",
        "        const FACE = 3;",
        "        const LINE_SPACING = 5;",
        "        const FIELDS = 7; // x, w, h, advance, offsetY, y, atlas class",
        "        const GLYPHS = [",
    ]
    for code in range(32, 91):
        g = glyphs.get(code, [-1, 0, 0, 0, 0, 0, 0])
        lines.append("            " + ", ".join(map(str, g)) + f", // {code}")
    lines += [
        "        ];", "",
        "        function glyph(code as Number) as Array<Number>? {",
        "            if (code < 32 || code > 90) { return null; }",
        "            var base = (code - 32) * FIELDS;",
        "            if (GLYPHS[base] < 0) { return null; }",
        "            return GLYPHS.slice(base, base + FIELDS);",
        "        }", "    }", "}", "",
    ]
    (ROOT / "app/source/Render/MenuFont.mc").write_text("\n".join(lines))
    print(f"Packed {len(glyphs)} menu glyphs from existing atlases.")


if __name__ == "__main__":
    main()
