import Toybox.Lang;

// GENERATED by tools/pack_ui_sprites.py -- do not edit.
//
// port of SpriteDatabase.cs, whose fields are wired in the Unity
// scene rather than in the C#. Each constant is [atlasClass, x, y, w,
// h], the same shape GameData.spriteRef returns, so the display list
// treats a UI sprite and a Digimon sprite identically.
//
// A field the scene leaves unassigned is emitted as null, and the
// generator prints it: an unassigned sprite is a hole in the port, not
// a detail to discover at runtime.
module Kaisa {
    module Sprites {
        const TAKUYA = [
            [1, 256, 352, 32, 32],
            [1, 288, 352, 32, 32],
            [1, 320, 352, 32, 32],
            [1, 352, 352, 32, 32],
            [1, 384, 352, 32, 32],
            [1, 416, 352, 32, 32],
            [1, 448, 352, 32, 32],
            [1, 480, 352, 32, 32],
            [1, 512, 352, 32, 32],
            [1, 544, 352, 32, 32]
        ];
        const KOJI = [
            [1, 736, 352, 32, 32],
            [1, 0, 384, 32, 32],
            [1, 32, 384, 32, 32],
            [1, 64, 384, 32, 32],
            [1, 96, 384, 32, 32],
            [1, 128, 384, 32, 32],
            [1, 160, 384, 32, 32],
            [1, 192, 384, 32, 32],
            [1, 224, 384, 32, 32],
            [1, 256, 384, 32, 32]
        ];
        const ZOE = [
            [1, 448, 384, 32, 32],
            [1, 480, 384, 32, 32],
            [1, 512, 384, 32, 32],
            [1, 544, 384, 32, 32],
            [1, 576, 384, 32, 32],
            [1, 608, 384, 32, 32],
            [1, 640, 384, 32, 32],
            [1, 672, 384, 32, 32],
            [1, 704, 384, 32, 32],
            [1, 736, 384, 32, 32]
        ];
        const JP = [
            [1, 160, 416, 32, 32],
            [1, 192, 416, 32, 32],
            [1, 224, 416, 32, 32],
            [1, 256, 416, 32, 32],
            [1, 288, 416, 32, 32],
            [1, 320, 416, 32, 32],
            [1, 352, 416, 32, 32],
            [1, 384, 416, 32, 32],
            [1, 416, 416, 32, 32],
            [1, 448, 416, 32, 32]
        ];
        const TOMMY = [
            [1, 640, 416, 32, 32],
            [1, 672, 416, 32, 32],
            [1, 704, 416, 32, 32],
            [1, 736, 416, 32, 32],
            [1, 0, 448, 32, 32],
            [1, 32, 448, 32, 32],
            [1, 64, 448, 32, 32],
            [1, 96, 448, 32, 32],
            [1, 128, 448, 32, 32],
            [1, 160, 448, 32, 32]
        ];
        const KOICHI = [
            [1, 352, 448, 32, 32],
            [1, 384, 448, 32, 32],
            [1, 416, 448, 32, 32],
            [1, 448, 448, 32, 32],
            [1, 480, 448, 32, 32],
            [1, 512, 448, 32, 32],
            [1, 544, 448, 32, 32],
            [1, 576, 448, 32, 32],
            [1, 608, 448, 32, 32],
            [1, 640, 448, 32, 32]
        ];
        const EMPTY_SPRITE = null;
        const BLACK_SCREEN = [1, 416, 672, 32, 32];
        const BLACK_BARS = [1, 256, 672, 32, 32];
        const ARROWS = [1, 288, 672, 32, 32];
        const ARROWS_SMALL = [1, 352, 672, 32, 32];
        const INVERTED_ARROWS_SMALL = [1, 384, 672, 32, 32];
        const TRIGGER_EVENT = [1, 160, 64, 32, 32];
        const EYES = [
            [1, 192, 64, 32, 32],
            [1, 224, 64, 32, 32]
        ];
        const LOADING = [1, 64, 960, 32, 32];
        const LOADING_COMPLETE = [3, 586, 0, 32, 82];
        const PRESS_A_BUTTON = [
            [1, 352, 128, 32, 32],
            [1, 384, 128, 32, 32]
        ];
        const HOURGLASS = [1, 448, 128, 32, 32];
        const ERROR = [1, 416, 128, 32, 32];
        const REWARD_BACKGROUND = [
            [1, 32, 64, 32, 32],
            [1, 64, 64, 32, 32],
            [1, 96, 64, 32, 32],
            [1, 128, 64, 32, 32]
        ];
        const REWARDS = [
            [3, 67, 0, 3, 9],
            [3, 538, 0, 16, 16],
            [3, 554, 0, 16, 16],
            [3, 570, 0, 16, 16]
        ];
        const BUBBLE = [1, 352, 96, 32, 32];
        const DIGISTORM = [
            [3, 881, 0, 40, 32],
            [3, 921, 0, 40, 32]
        ];
        const DEFEATED_SYMBOL = [3, 964, 0, 6, 7];
        const GAME_START_CLOUDS = [3, 625, 0, 76, 32];
        const GAME_START_TRAILMON = [3, 701, 0, 118, 15];
        const GAME_START_SPIRIT_PLATFORM = [3, 819, 0, 22, 3];
        const MAIN_MENU = [
            [1, 544, 640, 32, 32],
            [1, 576, 640, 32, 32],
            [1, 608, 640, 32, 32],
            [1, 640, 640, 32, 32],
            [1, 672, 640, 32, 32],
            [1, 704, 640, 32, 32],
            [1, 736, 640, 32, 32]
        ];
        const MAP_DISTANCE_SCREEN = [1, 352, 928, 32, 32];
        const STATUS_DISTANCE = [1, 736, 672, 32, 32];
        const STATUS_LEVEL = [1, 0, 704, 32, 32];
        const STATUS_VICTORIES = [1, 32, 704, 32, 32];
        const STATUS_DDOCK = [
            [1, 64, 704, 32, 32],
            [1, 96, 704, 32, 32],
            [1, 128, 704, 32, 32],
            [1, 160, 704, 32, 32]
        ];
        const STATUS_DDOCK_EMPTY = [0, 240, 1656, 24, 24];
        const GAME_SECTIONS = [
            [1, 512, 704, 32, 32],
            [1, 448, 704, 32, 32],
            [1, 480, 704, 32, 32]
        ];
        const GAMES_REWARD = [
            [1, 544, 704, 32, 32],
            [1, 576, 704, 32, 32],
            [1, 608, 704, 32, 32]
        ];
        const GAMES_TRAVEL = [
            [1, 640, 704, 32, 32],
            [1, 672, 704, 32, 32],
            [1, 704, 704, 32, 32],
            [1, 736, 704, 32, 32]
        ];
        const GAMES_SCORE = [3, 402, 0, 32, 5];
        const GAMES_DISTANCE = [3, 466, 0, 8, 8];
        const DATABASE_SECTIONS = [
            [1, 736, 832, 32, 32],
            [1, 0, 864, 32, 32],
            [1, 32, 864, 32, 32],
            [1, 64, 864, 32, 32],
            [1, 96, 864, 32, 32],
            [1, 128, 864, 32, 32],
            [1, 160, 864, 32, 32],
            [1, 288, 864, 32, 32]
        ];
        const DATABASE_SPIRIT_FUSION = [1, 192, 864, 32, 32];
        const ELEMENTS = [
            [1, 448, 864, 32, 32],
            [1, 480, 864, 32, 32],
            [1, 512, 864, 32, 32],
            [1, 544, 864, 32, 32],
            [1, 576, 864, 32, 32],
            [1, 608, 864, 32, 32],
            [1, 640, 864, 32, 32],
            [1, 672, 864, 32, 32],
            [1, 704, 864, 32, 32],
            [1, 736, 864, 32, 32]
        ];
        const ELEMENT_NAMES = [
            [3, 100, 0, 30, 5],
            [3, 130, 0, 30, 5],
            [3, 160, 0, 30, 5],
            [3, 190, 0, 30, 5],
            [3, 220, 0, 30, 5],
            [3, 250, 0, 30, 5],
            [3, 280, 0, 30, 5],
            [3, 310, 0, 30, 5],
            [3, 340, 0, 30, 5],
            [3, 370, 0, 32, 5]
        ];
        const DATABASE_PAGES = [
            [1, 512, 896, 32, 32],
            [1, 544, 896, 32, 32],
            [1, 576, 896, 32, 32]
        ];
        const DATABASE_DDOCKS = [
            [1, 192, 704, 32, 32],
            [1, 224, 704, 32, 32],
            [1, 256, 704, 32, 32],
            [1, 288, 704, 32, 32]
        ];
        const DATABASE_SEARCH_OPTIONS = [
            [1, 32, 896, 32, 32],
            [1, 64, 896, 32, 32],
            [1, 96, 896, 32, 32]
        ];
        const DIGITS_OK = [1, 320, 704, 32, 32];
        const DIGITS_ERROR = [1, 352, 704, 32, 32];
        const CAMP = [
            [0, 312, 1656, 24, 24],
            [0, 336, 1656, 24, 24]
        ];
        const GIVE_POWER = [1, 512, 64, 32, 32];
        const GIVE_POWER_INVERTED = [1, 480, 64, 32, 32];
        const GIVE_MASSIVE_POWER = [1, 640, 64, 32, 32];
        const GIVE_MASSIVE_POWER_INVERTED = [1, 576, 64, 32, 32];
        const CURTAIN = [1, 544, 64, 32, 32];
        const CURTAIN_SPECIAL = [
            [1, 256, 96, 32, 32],
            [1, 288, 96, 32, 32]
        ];
        const D_TECTOR = [1, 608, 64, 32, 32];
        const ANIM_DISTANCE = [3, 466, 0, 8, 8];
        const ANCIENT_SPIRAL = [
            [1, 160, 96, 32, 32],
            [1, 192, 96, 32, 32]
        ];
        const ANCIENT_CIRCLE = [
            [1, 640, 96, 32, 32],
            [1, 672, 96, 32, 32],
            [1, 704, 96, 32, 32]
        ];
        const STEAL_SPIRIT_ATTRACTOR = [3, 961, 0, 3, 24];
        const BATTLE_MAIN_MENU = [
            [1, 640, 736, 32, 32],
            [1, 672, 736, 32, 32],
            [1, 704, 736, 32, 32],
            [1, 736, 736, 32, 32]
        ];
        const BATTLE_COMBAT_MENU = [
            [1, 352, 768, 32, 32],
            [1, 384, 768, 32, 32],
            [1, 416, 768, 32, 32],
            [1, 448, 768, 32, 32],
            [1, 480, 768, 32, 32]
        ];
        const BATTLE_ATTACK_MENU = [
            [1, 64, 800, 32, 32],
            [1, 96, 800, 32, 32],
            [1, 128, 800, 32, 32]
        ];
        const BATTLE_DISOBEY = [3, 70, 0, 30, 5];
        const BATTLE_ATTACK_COLLISION = [3, 60, 0, 7, 24];
        const BATTLE_ATTACK_COLLISION_BIG = [3, 45, 0, 15, 32];
        const BATTLE_ATTACK_COLLISION_SMALL = [3, 618, 0, 7, 15];
        const BATTLE_EXPLOSION = [
            [0, 192, 1656, 24, 24],
            [0, 216, 1656, 24, 24]
        ];
        const BATTLE_CALL_POINTS_SCREEN = [1, 320, 800, 32, 32];
        const BATTLE_CALL_POINTS_CHOOSER = [1, 352, 800, 32, 32];
        const BATTLE_GAINING_SP = [
            [1, 256, 800, 32, 32],
            [1, 288, 800, 32, 32]
        ];
        const JACKPOT_PAD = [0, 264, 1656, 24, 24];
        const JACKPOT_KEYS = [
            [3, 865, 0, 8, 12],
            [3, 873, 0, 8, 12],
            [3, 841, 0, 12, 8],
            [3, 853, 0, 12, 8]
        ];
        const DIGI_HUNTER_ARROWS = [
            [3, 970, 0, 3, 6],
            [3, 973, 0, 6, 3]
        ];
        const DIGI_HUNTER_FACES = [
            [3, 490, 0, 8, 8],
            [3, 482, 0, 8, 8]
        ];
        const DIGI_HUNTER_EXPLOSION = [3, 498, 0, 8, 8];
        const SPEED_RUNNER_ROCKET = [3, 474, 0, 8, 8];
        const SPEED_RUNNER_ROCKET_EXPLOSION = [3, 506, 0, 7, 6];
        const SPEED_RUNNER_ROCKET_ASTEROID = [3, 513, 0, 3, 5];
        const SPEED_RUNNER_ROCKET_SPEED_MARK = [3, 516, 0, 6, 32];
        const SPEED_RUNNER_ROCKET_FINISH = [3, 522, 0, 16, 16];
        const SPIRIT_ABSORBER = [
            [3, 979, 0, 16, 32],
            [3, 995, 0, 16, 32]
        ];
        const SPIRIT_EXPLOSION = [2, 280, 0, 14, 16];
        // GENERATED reverse lookup, debug only: [atlasClass, x, y, w, h]
        // -> the SpriteDatabase field name the original would print.
        // Array fields print as `field_index`, matching the reference.
        (:debug) const TRACE_NAMES = [
            ["takuya_0", 1, 256, 352],
            ["takuya_1", 1, 288, 352],
            ["takuya_2", 1, 320, 352],
            ["takuya_3", 1, 352, 352],
            ["takuya_4", 1, 384, 352],
            ["takuya_5", 1, 416, 352],
            ["takuya_6", 1, 448, 352],
            ["takuya_7", 1, 480, 352],
            ["takuya_8", 1, 512, 352],
            ["takuya_9", 1, 544, 352],
            ["koji_0", 1, 736, 352],
            ["koji_1", 1, 0, 384],
            ["koji_2", 1, 32, 384],
            ["koji_3", 1, 64, 384],
            ["koji_4", 1, 96, 384],
            ["koji_5", 1, 128, 384],
            ["koji_6", 1, 160, 384],
            ["koji_7", 1, 192, 384],
            ["koji_8", 1, 224, 384],
            ["koji_9", 1, 256, 384],
            ["zoe_0", 1, 448, 384],
            ["zoe_1", 1, 480, 384],
            ["zoe_2", 1, 512, 384],
            ["zoe_3", 1, 544, 384],
            ["zoe_4", 1, 576, 384],
            ["zoe_5", 1, 608, 384],
            ["zoe_6", 1, 640, 384],
            ["zoe_7", 1, 672, 384],
            ["zoe_8", 1, 704, 384],
            ["zoe_9", 1, 736, 384],
            ["jp_0", 1, 160, 416],
            ["jp_1", 1, 192, 416],
            ["jp_2", 1, 224, 416],
            ["jp_3", 1, 256, 416],
            ["jp_4", 1, 288, 416],
            ["jp_5", 1, 320, 416],
            ["jp_6", 1, 352, 416],
            ["jp_7", 1, 384, 416],
            ["jp_8", 1, 416, 416],
            ["jp_9", 1, 448, 416],
            ["tommy_0", 1, 640, 416],
            ["tommy_1", 1, 672, 416],
            ["tommy_2", 1, 704, 416],
            ["tommy_3", 1, 736, 416],
            ["tommy_4", 1, 0, 448],
            ["tommy_5", 1, 32, 448],
            ["tommy_6", 1, 64, 448],
            ["tommy_7", 1, 96, 448],
            ["tommy_8", 1, 128, 448],
            ["tommy_9", 1, 160, 448],
            ["koichi_0", 1, 352, 448],
            ["koichi_1", 1, 384, 448],
            ["koichi_2", 1, 416, 448],
            ["koichi_3", 1, 448, 448],
            ["koichi_4", 1, 480, 448],
            ["koichi_5", 1, 512, 448],
            ["koichi_6", 1, 544, 448],
            ["koichi_7", 1, 576, 448],
            ["koichi_8", 1, 608, 448],
            ["koichi_9", 1, 640, 448],
            ["blackScreen", 1, 416, 672],
            ["blackBars", 1, 256, 672],
            ["arrows", 1, 288, 672],
            ["arrowsSmall", 1, 352, 672],
            ["invertedArrowsSmall", 1, 384, 672],
            ["triggerEvent", 1, 160, 64],
            ["eyes_0", 1, 192, 64],
            ["eyes_1", 1, 224, 64],
            ["loading", 1, 64, 960],
            ["loadingComplete", 3, 586, 0],
            ["pressAButton_0", 1, 352, 128],
            ["pressAButton_1", 1, 384, 128],
            ["hourglass", 1, 448, 128],
            ["error", 1, 416, 128],
            ["rewardBackground_0", 1, 32, 64],
            ["rewardBackground_1", 1, 64, 64],
            ["rewardBackground_2", 1, 96, 64],
            ["rewardBackground_3", 1, 128, 64],
            ["rewards_0", 3, 67, 0],
            ["rewards_1", 3, 538, 0],
            ["rewards_2", 3, 554, 0],
            ["rewards_3", 3, 570, 0],
            ["bubble", 1, 352, 96],
            ["digistorm_0", 3, 881, 0],
            ["digistorm_1", 3, 921, 0],
            ["defeatedSymbol", 3, 964, 0],
            ["gameStart_clouds", 3, 625, 0],
            ["gameStart_trailmon", 3, 701, 0],
            ["gameStart_spiritPlatform", 3, 819, 0],
            ["mainMenu_0", 1, 544, 640],
            ["mainMenu_1", 1, 576, 640],
            ["mainMenu_2", 1, 608, 640],
            ["mainMenu_3", 1, 640, 640],
            ["mainMenu_4", 1, 672, 640],
            ["mainMenu_5", 1, 704, 640],
            ["mainMenu_6", 1, 736, 640],
            ["map_distanceScreen", 1, 352, 928],
            ["status_distance", 1, 736, 672],
            ["status_level", 1, 0, 704],
            ["status_victories", 1, 32, 704],
            ["status_ddock_0", 1, 64, 704],
            ["status_ddock_1", 1, 96, 704],
            ["status_ddock_2", 1, 128, 704],
            ["status_ddock_3", 1, 160, 704],
            ["status_ddockEmpty", 0, 240, 1656],
            ["game_sections_0", 1, 512, 704],
            ["game_sections_1", 1, 448, 704],
            ["game_sections_2", 1, 480, 704],
            ["games_reward_0", 1, 544, 704],
            ["games_reward_1", 1, 576, 704],
            ["games_reward_2", 1, 608, 704],
            ["games_travel_0", 1, 640, 704],
            ["games_travel_1", 1, 672, 704],
            ["games_travel_2", 1, 704, 704],
            ["games_travel_3", 1, 736, 704],
            ["games_score", 3, 402, 0],
            ["games_distance", 3, 466, 0],
            ["database_sections_0", 1, 736, 832],
            ["database_sections_1", 1, 0, 864],
            ["database_sections_2", 1, 32, 864],
            ["database_sections_3", 1, 64, 864],
            ["database_sections_4", 1, 96, 864],
            ["database_sections_5", 1, 128, 864],
            ["database_sections_6", 1, 160, 864],
            ["database_sections_7", 1, 288, 864],
            ["database_spirit_fusion", 1, 192, 864],
            ["elements_0", 1, 448, 864],
            ["elements_1", 1, 480, 864],
            ["elements_2", 1, 512, 864],
            ["elements_3", 1, 544, 864],
            ["elements_4", 1, 576, 864],
            ["elements_5", 1, 608, 864],
            ["elements_6", 1, 640, 864],
            ["elements_7", 1, 672, 864],
            ["elements_8", 1, 704, 864],
            ["elements_9", 1, 736, 864],
            ["elementNames_0", 3, 100, 0],
            ["elementNames_1", 3, 130, 0],
            ["elementNames_2", 3, 160, 0],
            ["elementNames_3", 3, 190, 0],
            ["elementNames_4", 3, 220, 0],
            ["elementNames_5", 3, 250, 0],
            ["elementNames_6", 3, 280, 0],
            ["elementNames_7", 3, 310, 0],
            ["elementNames_8", 3, 340, 0],
            ["elementNames_9", 3, 370, 0],
            ["database_pages_0", 1, 512, 896],
            ["database_pages_1", 1, 544, 896],
            ["database_pages_2", 1, 576, 896],
            ["database_ddocks_0", 1, 192, 704],
            ["database_ddocks_1", 1, 224, 704],
            ["database_ddocks_2", 1, 256, 704],
            ["database_ddocks_3", 1, 288, 704],
            ["database_searchOptions_0", 1, 32, 896],
            ["database_searchOptions_1", 1, 64, 896],
            ["database_searchOptions_2", 1, 96, 896],
            ["digits_ok", 1, 320, 704],
            ["digits_error", 1, 352, 704],
            ["camp_0", 0, 312, 1656],
            ["camp_1", 0, 336, 1656],
            ["givePower", 1, 512, 64],
            ["givePowerInverted", 1, 480, 64],
            ["giveMassivePower", 1, 640, 64],
            ["giveMassivePowerInverted", 1, 576, 64],
            ["curtain", 1, 544, 64],
            ["curtainSpecial_0", 1, 256, 96],
            ["curtainSpecial_1", 1, 288, 96],
            ["dTector", 1, 608, 64],
            ["animDistance", 3, 466, 0],
            ["ancientSpiral_0", 1, 160, 96],
            ["ancientSpiral_1", 1, 192, 96],
            ["ancientCircle_0", 1, 640, 96],
            ["ancientCircle_1", 1, 672, 96],
            ["ancientCircle_2", 1, 704, 96],
            ["stealSpiritAttractor", 3, 961, 0],
            ["battle_mainMenu_0", 1, 640, 736],
            ["battle_mainMenu_1", 1, 672, 736],
            ["battle_mainMenu_2", 1, 704, 736],
            ["battle_mainMenu_3", 1, 736, 736],
            ["battle_combatMenu_0", 1, 352, 768],
            ["battle_combatMenu_1", 1, 384, 768],
            ["battle_combatMenu_2", 1, 416, 768],
            ["battle_combatMenu_3", 1, 448, 768],
            ["battle_combatMenu_4", 1, 480, 768],
            ["battle_attackMenu_0", 1, 64, 800],
            ["battle_attackMenu_1", 1, 96, 800],
            ["battle_attackMenu_2", 1, 128, 800],
            ["battle_disobey", 3, 70, 0],
            ["battle_attackCollision", 3, 60, 0],
            ["battle_attackCollisionBig", 3, 45, 0],
            ["battle_attackCollisionSmall", 3, 618, 0],
            ["battle_explosion_0", 0, 192, 1656],
            ["battle_explosion_1", 0, 216, 1656],
            ["battle_callPoints_screen", 1, 320, 800],
            ["battle_callPoints_chooser", 1, 352, 800],
            ["battle_gainingSP_0", 1, 256, 800],
            ["battle_gainingSP_1", 1, 288, 800],
            ["jackpot_pad", 0, 264, 1656],
            ["jackpot_keys_0", 3, 865, 0],
            ["jackpot_keys_1", 3, 873, 0],
            ["jackpot_keys_2", 3, 841, 0],
            ["jackpot_keys_3", 3, 853, 0],
            ["digiHunter_arrows_0", 3, 970, 0],
            ["digiHunter_arrows_1", 3, 973, 0],
            ["digiHunter_faces_0", 3, 490, 0],
            ["digiHunter_faces_1", 3, 482, 0],
            ["digiHunter_explosion", 3, 498, 0],
            ["speedRunner_rocket", 3, 474, 0],
            ["speedRunner_rocketExplosion", 3, 506, 0],
            ["speedRunner_rocketAsteroid", 3, 513, 0],
            ["speedRunner_rocketSpeedMark", 3, 516, 0],
            ["speedRunner_rocketFinish", 3, 522, 0],
            ["spirit_absorber_0", 3, 979, 0],
            ["spirit_absorber_1", 3, 995, 0],
            ["spirit_explosion", 2, 280, 0],
        ];

        (:debug)
        function nameOf(ref as Array<Number>?) as String {
            if (ref == null) { return "null"; }
            for (var i = 0; i < TRACE_NAMES.size(); i += 1) {
                var e = TRACE_NAMES[i];
                if (e[1] == ref[0] && e[2] == ref[1] && e[3] == ref[2]) {
                    return e[0];
                }
            }
            return "sprite(" + ref[0] + "," + ref[1] + "," + ref[2] + ")";
        }
    }
}
