import Toybox.Lang;

// GENERATED by tools/pack_ui_sprites.py -- do not edit.
//
// port of SpriteDatabase.cs, whose fields are wired in the Unity
// scene rather than in the C#. Each constant is [atlasClass, x, y, w,
// h], the same shape GameData.spriteRef returns, so the display list
// treats a UI sprite and a Digimon sprite identically.
//
// A field the scene leaves unassigned is emitted as null, and the
// generator prints it: an unassigned sprite is a hole in the port, not
// a detail to discover at runtime.
module Kaisa {
    module Sprites {
        const TAKUYA = [
            [1, 256, 352, 32, 32],
            [1, 288, 352, 32, 32],
            [1, 320, 352, 32, 32],
            [1, 352, 352, 32, 32],
            [1, 384, 352, 32, 32],
            [1, 416, 352, 32, 32],
            [1, 448, 352, 32, 32],
            [1, 480, 352, 32, 32],
            [1, 512, 352, 32, 32],
            [1, 544, 352, 32, 32]
        ];
        const KOJI = [
            [1, 736, 352, 32, 32],
            [1, 0, 384, 32, 32],
            [1, 32, 384, 32, 32],
            [1, 64, 384, 32, 32],
            [1, 96, 384, 32, 32],
            [1, 128, 384, 32, 32],
            [1, 160, 384, 32, 32],
            [1, 192, 384, 32, 32],
            [1, 224, 384, 32, 32],
            [1, 256, 384, 32, 32]
        ];
        const ZOE = [
            [1, 448, 384, 32, 32],
            [1, 480, 384, 32, 32],
            [1, 512, 384, 32, 32],
            [1, 544, 384, 32, 32],
            [1, 576, 384, 32, 32],
            [1, 608, 384, 32, 32],
            [1, 640, 384, 32, 32],
            [1, 672, 384, 32, 32],
            [1, 704, 384, 32, 32],
            [1, 736, 384, 32, 32]
        ];
        const JP = [
            [1, 160, 416, 32, 32],
            [1, 192, 416, 32, 32],
            [1, 224, 416, 32, 32],
            [1, 256, 416, 32, 32],
            [1, 288, 416, 32, 32],
            [1, 320, 416, 32, 32],
            [1, 352, 416, 32, 32],
            [1, 384, 416, 32, 32],
            [1, 416, 416, 32, 32],
            [1, 448, 416, 32, 32]
        ];
        const TOMMY = [
            [1, 640, 416, 32, 32],
            [1, 672, 416, 32, 32],
            [1, 704, 416, 32, 32],
            [1, 736, 416, 32, 32],
            [1, 0, 448, 32, 32],
            [1, 32, 448, 32, 32],
            [1, 64, 448, 32, 32],
            [1, 96, 448, 32, 32],
            [1, 128, 448, 32, 32],
            [1, 160, 448, 32, 32]
        ];
        const KOICHI = [
            [1, 352, 448, 32, 32],
            [1, 384, 448, 32, 32],
            [1, 416, 448, 32, 32],
            [1, 448, 448, 32, 32],
            [1, 480, 448, 32, 32],
            [1, 512, 448, 32, 32],
            [1, 544, 448, 32, 32],
            [1, 576, 448, 32, 32],
            [1, 608, 448, 32, 32],
            [1, 640, 448, 32, 32]
        ];
        const EMPTY_SPRITE = null;
        const BLACK_SCREEN = [1, 416, 672, 32, 32];
        const BLACK_BARS = [1, 256, 672, 32, 32];
        const ARROWS = [1, 288, 672, 32, 32];
        const ARROWS_SMALL = [1, 352, 672, 32, 32];
        const INVERTED_ARROWS_SMALL = [1, 384, 672, 32, 32];
        const TRIGGER_EVENT = [1, 160, 64, 32, 32];
        const EYES = [
            [1, 192, 64, 32, 32],
            [1, 224, 64, 32, 32]
        ];
        const LOADING = [1, 64, 960, 32, 32];
        const LOADING_COMPLETE = [3, 586, 0, 32, 82];
        const PRESS_A_BUTTON = [
            [1, 352, 128, 32, 32],
            [1, 384, 128, 32, 32]
        ];
        const HOURGLASS = [1, 448, 128, 32, 32];
        const ERROR = [1, 416, 128, 32, 32];
        const REWARD_BACKGROUND = [
            [1, 32, 64, 32, 32],
            [1, 64, 64, 32, 32],
            [1, 96, 64, 32, 32],
            [1, 128, 64, 32, 32]
        ];
        const REWARDS = [
            [3, 522, 0, 16, 16],
            [3, 538, 0, 16, 16],
            [3, 554, 0, 16, 16],
            [3, 570, 0, 16, 16]
        ];
        const BUBBLE = [1, 352, 96, 32, 32];
        const DIGISTORM = [
            [3, 881, 0, 40, 32],
            [3, 921, 0, 40, 32]
        ];
        const DEFEATED_SYMBOL = [3, 964, 0, 6, 7];
        const GAME_START_CLOUDS = [3, 625, 0, 76, 32];
        const GAME_START_TRAILMON = [3, 701, 0, 118, 15];
        const GAME_START_SPIRIT_PLATFORM = [3, 819, 0, 22, 3];
        const MAIN_MENU = [
            [1, 544, 640, 32, 32],
            [1, 576, 640, 32, 32],
            [1, 608, 640, 32, 32],
            [1, 640, 640, 32, 32],
            [1, 672, 640, 32, 32],
            [1, 704, 640, 32, 32],
            [1, 736, 640, 32, 32]
        ];
        const MAP_DISTANCE_SCREEN = [1, 352, 928, 32, 32];
        const STATUS_DISTANCE = [1, 736, 672, 32, 32];
        const STATUS_LEVEL = [1, 0, 704, 32, 32];
        const STATUS_VICTORIES = [1, 32, 704, 32, 32];
        const STATUS_DDOCK = [
            [1, 64, 704, 32, 32],
            [1, 96, 704, 32, 32],
            [1, 128, 704, 32, 32],
            [1, 160, 704, 32, 32]
        ];
        const STATUS_DDOCK_EMPTY = [0, 240, 1656, 24, 24];
        const GAME_SECTIONS = [
            [1, 512, 704, 32, 32],
            [1, 448, 704, 32, 32],
            [1, 480, 704, 32, 32]
        ];
        const GAMES_REWARD = [
            [1, 544, 704, 32, 32],
            [1, 576, 704, 32, 32],
            [1, 608, 704, 32, 32]
        ];
        const GAMES_TRAVEL = [
            [1, 640, 704, 32, 32],
            [1, 672, 704, 32, 32],
            [1, 704, 704, 32, 32],
            [1, 736, 704, 32, 32]
        ];
        const GAMES_SCORE = [3, 370, 0, 32, 5];
        const GAMES_DISTANCE = [3, 402, 0, 32, 5];
        const DATABASE_SECTIONS = [
            [1, 736, 832, 32, 32],
            [1, 0, 864, 32, 32],
            [1, 32, 864, 32, 32],
            [1, 64, 864, 32, 32],
            [1, 96, 864, 32, 32],
            [1, 128, 864, 32, 32],
            [1, 160, 864, 32, 32],
            [1, 288, 864, 32, 32]
        ];
        const DATABASE_SPIRIT_FUSION = [1, 192, 864, 32, 32];
        const ELEMENTS = [
            [1, 448, 864, 32, 32],
            [1, 480, 864, 32, 32],
            [1, 512, 864, 32, 32],
            [1, 544, 864, 32, 32],
            [1, 576, 864, 32, 32],
            [1, 608, 864, 32, 32],
            [1, 640, 864, 32, 32],
            [1, 672, 864, 32, 32],
            [1, 704, 864, 32, 32],
            [1, 736, 864, 32, 32]
        ];
        const ELEMENT_NAMES = [
            [3, 70, 0, 30, 5],
            [3, 100, 0, 30, 5],
            [3, 130, 0, 30, 5],
            [3, 160, 0, 30, 5],
            [3, 190, 0, 30, 5],
            [3, 220, 0, 30, 5],
            [3, 250, 0, 30, 5],
            [3, 280, 0, 30, 5],
            [3, 310, 0, 30, 5],
            [3, 340, 0, 30, 5]
        ];
        const DATABASE_PAGES = [
            [1, 512, 896, 32, 32],
            [1, 544, 896, 32, 32],
            [1, 576, 896, 32, 32]
        ];
        const DATABASE_DDOCKS = [
            [1, 192, 704, 32, 32],
            [1, 224, 704, 32, 32],
            [1, 256, 704, 32, 32],
            [1, 288, 704, 32, 32]
        ];
        const DATABASE_SEARCH_OPTIONS = [
            [1, 32, 896, 32, 32],
            [1, 64, 896, 32, 32],
            [1, 96, 896, 32, 32]
        ];
        const DIGITS_OK = [1, 320, 704, 32, 32];
        const DIGITS_ERROR = [1, 352, 704, 32, 32];
        const CAMP = [
            [0, 312, 1656, 24, 24],
            [0, 336, 1656, 24, 24]
        ];
        const GIVE_POWER = [1, 512, 64, 32, 32];
        const GIVE_POWER_INVERTED = [1, 480, 64, 32, 32];
        const GIVE_MASSIVE_POWER = [1, 640, 64, 32, 32];
        const GIVE_MASSIVE_POWER_INVERTED = [1, 576, 64, 32, 32];
        const CURTAIN = [1, 544, 64, 32, 32];
        const CURTAIN_SPECIAL = [
            [1, 256, 96, 32, 32],
            [1, 288, 96, 32, 32]
        ];
        const D_TECTOR = [1, 608, 64, 32, 32];
        const ANIM_DISTANCE = [3, 402, 0, 32, 5];
        const ANCIENT_SPIRAL = [
            [1, 160, 96, 32, 32],
            [1, 192, 96, 32, 32]
        ];
        const ANCIENT_CIRCLE = [
            [1, 640, 96, 32, 32],
            [1, 672, 96, 32, 32],
            [1, 704, 96, 32, 32]
        ];
        const STEAL_SPIRIT_ATTRACTOR = [3, 961, 0, 3, 24];
        const BATTLE_MAIN_MENU = [
            [1, 640, 736, 32, 32],
            [1, 672, 736, 32, 32],
            [1, 704, 736, 32, 32],
            [1, 736, 736, 32, 32]
        ];
        const BATTLE_COMBAT_MENU = [
            [1, 352, 768, 32, 32],
            [1, 384, 768, 32, 32],
            [1, 416, 768, 32, 32],
            [1, 448, 768, 32, 32],
            [1, 480, 768, 32, 32]
        ];
        const BATTLE_ATTACK_MENU = [
            [1, 64, 800, 32, 32],
            [1, 96, 800, 32, 32],
            [1, 128, 800, 32, 32]
        ];
        const BATTLE_DISOBEY = [3, 67, 0, 3, 9];
        const BATTLE_ATTACK_COLLISION = [3, 60, 0, 7, 24];
        const BATTLE_ATTACK_COLLISION_BIG = [3, 45, 0, 15, 32];
        const BATTLE_ATTACK_COLLISION_SMALL = [3, 618, 0, 7, 15];
        const BATTLE_EXPLOSION = [
            [0, 192, 1656, 24, 24],
            [0, 216, 1656, 24, 24]
        ];
        const BATTLE_CALL_POINTS_SCREEN = [1, 320, 800, 32, 32];
        const BATTLE_CALL_POINTS_CHOOSER = [1, 352, 800, 32, 32];
        const BATTLE_GAINING_SP = [
            [1, 256, 800, 32, 32],
            [1, 288, 800, 32, 32]
        ];
        const JACKPOT_PAD = [0, 264, 1656, 24, 24];
        const JACKPOT_KEYS = [
            [3, 865, 0, 8, 12],
            [3, 873, 0, 8, 12],
            [3, 841, 0, 12, 8],
            [3, 853, 0, 12, 8]
        ];
        const DIGI_HUNTER_ARROWS = [
            [3, 970, 0, 3, 6],
            [3, 973, 0, 6, 3]
        ];
        const DIGI_HUNTER_FACES = [
            [3, 490, 0, 8, 8],
            [3, 482, 0, 8, 8]
        ];
        const DIGI_HUNTER_EXPLOSION = [3, 498, 0, 8, 8];
        const SPEED_RUNNER_ROCKET = [3, 466, 0, 8, 8];
        const SPEED_RUNNER_ROCKET_EXPLOSION = [3, 474, 0, 8, 8];
        const SPEED_RUNNER_ROCKET_ASTEROID = [3, 506, 0, 7, 6];
        const SPEED_RUNNER_ROCKET_SPEED_MARK = [3, 513, 0, 3, 5];
        const SPEED_RUNNER_ROCKET_FINISH = [3, 516, 0, 6, 32];
        const SPIRIT_ABSORBER = [
            [3, 979, 0, 16, 32],
            [3, 995, 0, 16, 32]
        ];
        const SPIRIT_EXPLOSION = [2, 280, 0, 14, 16];

        // Art the C# fetches by name for something with no Digimon
        // row -- the Jackpot Box. Resolved here so nothing addresses
        // a sprite by name at runtime (ADR 7).
        const JACKPOT = [0, 384, 576, 24, 24];   // Digimon/jackpot
        const JACKPOT_ATTACK = [0, 408, 576, 24, 24];   // Digimon/jackpot_at
        const JACKPOT_SPIRIT = [0, 432, 576, 24, 24];   // Digimon/jackpot_sp
        // A sprite prints as its cell. The original prints a
        // SpriteDatabase field name instead; verify_anim.py maps those
        // to cells, so both sides of a diff say the same thing.
        (:debug)
        function nameOf(ref as Array<Number>?) as String {
            if (ref == null) { return "null"; }
            return "sprite(" + ref[0] + "," + ref[1] + "," + ref[2] + ")";
        }
    }
}
