import Toybox.Lang;

// GENERATED by tools/gen_text_probe.py from tools/text_probe.json --
// do not edit. The same spec tells tools/verify_text.py what this
// scene must look like once drawn, so the check cannot drift from the
// thing it checks (ADR 12).
//
// Every box is 6 game pixels tall, which is one line of Regular or
// Small and clears Big's 7 px digits without overlapping the next.
module TextProbe {
    const BOX_HEIGHT = 6;

    function build(root as ContainerBuilder) as Void {
        // Big is monospaced, and its letters carry a 2 px vertical bearing its digits do not
        add(root, "AGUMON 12", Kaisa.Font.BIG,
            0, 0, 32, Kaisa.Text.ANCHOR_UPPER_LEFT, false);
        // proportional advances, right-aligned, and the only punctuation any face has
        add(root, "LV 99!", Kaisa.Font.REGULAR,
            0, 9, 30, Kaisa.Text.ANCHOR_UPPER_RIGHT, false);
        // centre alignment rounds in game pixels, not device pixels
        add(root, "HP 1234", Kaisa.Font.SMALL,
            0, 15, 30, Kaisa.Text.ANCHOR_UPPER_CENTER, false);
        // parentheses have no glyph and are skipped entirely (ADR 10); the line break advances by lineSpacing
        add(root, "(BOSS)\nX9", Kaisa.Font.SMALL,
            0, 21, 30, Kaisa.Text.ANCHOR_UPPER_LEFT, false);
        // inverted text: the box paints ink and the glyphs paint the field colour
        add(root, "INV 07", Kaisa.Font.REGULAR,
            2, 26, 12, Kaisa.Text.ANCHOR_UPPER_LEFT, true);
    }

    function add(root as ContainerBuilder, text as String, font as Number,
                 x as Number, y as Number, w as Number, anchor as Number,
                 inverted as Boolean) as Void {
        var box = new TextBoxBuilder();
        box.setName("Probe");
        box.setSize(w, BOX_HEIGHT)
           .setPosition(x, y)
           .setFont(font)
           .setAlignment(anchor)
           .setTransparent(!inverted)
           .invertColors(inverted)
           .setText(text);
        root.addChild(box);
    }
}
